Repository scionproto/scion, pull requests merged in 2018-07, with the labels that each got.

#1607 BR: support for multiple external interfaces
  go/border/router.go
  go/border/rpkt/create.go
  go/border/rpkt/process.go
  go/border/rpkt/route.go
Labels: BR

#1648 Change SCIOND API path request flags
  go/lib/sciond/types.go
  go/sciond/internal/fetcher/fetcher.go
  proto/sciond.capnp
  python/integration/base_cli_srv.py
  python/lib/app/sciond.py
  python/lib/sciond_api/path_req.py
  python/scion_elem/scion_elem.py
  python/sciond/sciond.py
  python/test/lib/app/sciond_test.py
Labels: Breaking Change

#1656 Drop FORWARD_ONLY hop-field flag
  c/lib/scion/opaque_field.h
  c/lib/scion/scmp.h
  go/border/rpkt/path.go
  go/border/rpkt/route.go
  go/lib/scmp/scmp.go
  go/lib/spath/hop.go
  python/lib/flagtypes.py
  python/lib/packet/opaque_field.py
  python/lib/packet/scmp/errors.py
  python/lib/packet/scmp/types.py
  python/test/lib/packet/opaque_field_test.py
  tools/wireshark/scion.lua
Labels: Breaking Change

#1663 CS: Default to CS:GO
  python/topology/generator.py
Labels: CS

#1652 Remove sciond.SvcBR from SCIOND API
  go/lib/sciond/mock.go
  go/lib/sciond/sciond.go
  go/lib/sciond/types.go
  go/sciond/internal/servers/handlers.go
  go/sciond/server_test.go
  proto/common.capnp
  proto/sciond.capnp
  python/beacon_server/base.py
  python/beacon_server/core.py
  python/beacon_server/local.py
  python/cert_server/main.py
  python/lib/defines.py
  python/lib/packet/svc.py
  python/lib/topology.py
  python/lib/types.py
  python/lib/zk/zk.py
  python/path_server/base.py
  python/scion_elem/scion_elem.py
  python/sciond/sciond.py
  python/sibra_server/main.py
Labels: Breaking Change
