Repository scionproto/scion, pull requests merged in 2018-06, with the labels that each got.

#1593 Add quiet mode to scion-pki
  go/tools/scion-pki/internal/certs/gen.go
  go/tools/scion-pki/internal/certs/verify.go
  go/tools/scion-pki/internal/cmd/cmd.go
  go/tools/scion-pki/internal/conf/as.go
  go/tools/scion-pki/internal/conf/isd.go
  go/tools/scion-pki/internal/keys/gen.go
  go/tools/scion-pki/internal/pkicmn/pkicmn.go
  go/tools/scion-pki/internal/tmpl/as.go
  go/tools/scion-pki/internal/tmpl/isd.go
  go/tools/scion-pki/internal/trc/gen.go
  go/tools/scion-pki/internal/version/version.go
Labels: scion-pki

#1580 Enable SCIOND-less operation for snet
  go/lib/pathmgr/pathmgr.go
  go/lib/snet/conn.go
  go/lib/snet/integration_test.go
  go/lib/snet/snet.go
Labels: Breaking Change

#1587 BR: single internal interface per overlay
  go/border/gen.go
  go/border/ifid.go
  go/border/io.go
  go/border/netconf/interface.go
  go/border/rctx/io.go
  go/border/rctx/rctx.go
  go/border/revinfo.go
  go/border/router.go
  go/border/rpkt/create.go
  go/border/rpkt/extn_onehoppath.go
  go/border/rpkt/parse.go
  go/border/rpkt/path.go
  go/border/rpkt/process.go
  go/border/rpkt/route.go
  go/border/rpkt/rpkt.go
  go/border/rpkt/rpkt_test.go
  go/border/rpkt/validate.go
  go/border/setup.go
  go/lib/ctrl/ifid/ifid.go
  go/lib/topology/addr.go
  go/lib/topology/doc.go
  go/lib/topology/raw.go
  go/lib/topology/strip.go
  go/lib/topology/testdata/basic.json
  go/lib/topology/testdata/core.json
  go/lib/topology/topology.go
  go/lib/topology/topology_test.go
  python/beacon_server/base.py
  python/lib/topology.py
  python/scion_elem/scion_elem.py
  python/sciond/sciond.py
  python/test/lib/topology_test.py
  python/topology/generator.py
Labels: Breaking Change

#1612 Allow pkt validation hooks to filter packets.
  go/border/router.go
  go/border/rpkt/validate.go
Labels: BR

#1558 CSGO: Add Certificate Reissuance
  go/cert_srv/cert.go
  go/cert_srv/conf/conf.go
  go/cert_srv/io.go
  go/cert_srv/main.go
  go/cert_srv/reiss_handler.go
  go/cert_srv/reiss_tasks.go
  go/cert_srv/setup.go
  go/cert_srv/signed_util.go
  go/lib/as_conf/conf.go
  go/lib/as_conf/conf_test.go
  go/lib/as_conf/testdata/basic.yml
  go/lib/trust/store.go
  python/beacon_server/base.py
Labels: CS, SPKI

#1634 Consistent timestamps
  go/cert_srv/cert.go
  go/cert_srv/reiss_handler.go
  go/cert_srv/reiss_tasks.go
  go/lib/crypto/cert/cert.go
  go/lib/crypto/cert/cert_test.go
  go/lib/crypto/cert/chain_test.go
  go/lib/crypto/trc/trc.go
  go/lib/crypto/trc/trc_test.go
  go/lib/ctrl/path_mgmt/rev_info.go
  go/lib/sciond/types.go
  go/lib/util/time.go
  go/proto/sign.go
  go/tools/scion-pki/internal/certs/gen.go
  go/tools/scion-pki/internal/conf/as.go
  go/tools/scion-pki/internal/conf/isd.go
  go/tools/scion-pki/internal/trc/gen.go
  proto/drkey_mgmt.capnp
  proto/rev_info.capnp
  proto/sciond.capnp
  proto/sign.capnp
  python/lib/packet/proto_sign.py
Labels: Breaking Change

#1633 Cleaner separation of base AS package
  go/sig/base/core/as.go
  go/sig/base/core/map.go
  go/sig/main.go
Labels: SIG
