Repository scionproto/scion, pull requests merged in 2018-08, with the labels that each got.

#1731 Implement verification in SCIOND
  .circleci/config.yml
  env/pip3/requirements.txt
  go/cert_srv/conf/conf.go
  go/cert_srv/setup.go
  go/lib/addr/isdas.go
  go/lib/ctrl/signed_util.go
  go/lib/infra/common.go
  go/lib/infra/example/main.go
  go/lib/infra/messenger/messenger.go
  go/lib/infra/messenger/messenger_test.go
  go/lib/infra/modules/combinator/graph.go
  go/lib/infra/modules/combinator/testdata/14_compute_path.txt
  go/lib/infra/modules/segverifier/segverifier.go
  go/lib/infra/modules/trust/handlers.go
  go/lib/infra/modules/trust/helpers.go
  go/lib/infra/modules/trust/trust.go
  go/lib/infra/modules/trust/trust_test.go
  go/lib/topology/topology.go
  go/lib/util/debugid.go
  go/sciond/internal/fetcher/fetcher.go
  go/sciond/internal/servers/api.go
  go/sciond/internal/servers/handlers.go
  go/sciond/internal/servers/server.go
  go/sciond/main.go
  go/sciond/server_test.go
  python/topology/generator.py
Labels: sciond

#1757 PS: improve segments returned
  python/path_server/local.py
Labels: PS

#1786 Hide ExpTime in HopField instead offer a ExpTime method
  go/border/rpkt/extn_onehoppath.go
  go/border/rpkt/path.go
  go/lib/infra/modules/combinator/graph.go
  go/lib/pathdb/sqlite/sqlite_test.go
  go/lib/spath/hop.go
  go/lib/xtest/graph/graph.go
  python/lib/packet/pcb.py
  python/lib/path_combinator.py
  python/test/lib/path_combinator_test.py
  tools/wireshark/scion.lua
Labels: Breaking Change

#1808 sciond: Increase timeout for PathReply processing
  python/sciond/req.py
Labels: sciond

#1798 PS-DD: Add details about down seg sync
  doc/PathService.md
Labels: PS

#1783 Initial go PS
  go/lib/ctrl/path_mgmt/seg_recs.go
  go/lib/ctrl/path_mgmt/seg_reply.go
  go/lib/ctrl/seg/meta.go
  go/lib/ctrl/seg/seg.go
  go/lib/env/env.go
  go/lib/infra/common.go
  go/lib/infra/messenger/messenger.go
  go/lib/infra/messenger/mock.go
  go/lib/infra/modules/segsaver/segsaver.go
  go/lib/pathdb/sqlite/sqlite.go
  go/lib/topology/topology.go
  go/lib/xtest/graph/graph.go
  go/path_srv/internal/handlers/common.go
  go/path_srv/internal/handlers/segreg.go
  go/path_srv/internal/handlers/segreq.go
  go/path_srv/internal/handlers/segreqcore.go
  go/path_srv/internal/handlers/segreqnoncore.go
  go/path_srv/internal/handlers/segreqnoncore_test.go
  go/path_srv/internal/handlers/segrevoc.go
  go/path_srv/internal/handlers/segsync.go
  go/path_srv/internal/handlers/testdata/topology_as1_132.json
  go/path_srv/internal/handlers/testdata/topology_as2_211.json
  go/path_srv/internal/handlers/testdata/topology_as2_222.json
  go/path_srv/main.go
  go/sciond/internal/fetcher/fetcher.go
  python/topology/generator.py
Labels: PS
