Repository scionproto/scion, pull requests merged in 2018-09, with the labels that each got.

#1830 Introduce cleaner, to periodically clean the pathDB
  go/lib/ctrl/seg/seg.go
  go/lib/ctrl/seg/signed.go
  go/lib/pathdb/pathdb.go
  go/lib/pathdb/sqlite/schema.go
  go/lib/pathdb/sqlite/sqlite.go
  go/lib/pathdb/sqlite/sqlite_test.go
  go/path_srv/internal/cleaner/cleaner.go
  go/path_srv/main.go
Labels: PS

#1831 Introduce various convenience methods
  go/lib/ctrl/seg/meta.go
  go/lib/ctrl/seg/segs.go
  go/lib/ctrl/seg/segs_test.go
  go/lib/pathdb/query/query.go
  go/lib/revcache/revcache.go
  go/path_srv/internal/handlers/common.go
  go/path_srv/internal/handlers/segreq.go
  go/path_srv/internal/handlers/segreqcore.go
  go/path_srv/internal/handlers/segreqnoncore.go
  go/path_srv/internal/handlers/segreqnoncore_test.go
  go/path_srv/internal/segutil/segutil.go
  go/sciond/internal/fetcher/fetcher.go
Labels: PS

#1840 PS: Hold request until up-/core-segs are available
  go/Makefile
  go/lib/pathdb/mock_pathdb/mock_pathdb.go
  go/path_srv/internal/handlers/common.go
  go/path_srv/internal/handlers/common_test.go
  go/path_srv/internal/handlers/segreqcore.go
  go/path_srv/internal/handlers/segreqnoncore.go
Labels: PS

#1841 PS: Sync downSegs periodically not on receive
  go/lib/pathdb/query/query.go
  go/lib/pathdb/sqlite/sqlite.go
  go/path_srv/internal/addrutil/addrutil.go
  go/path_srv/internal/handlers/common.go
  go/path_srv/internal/handlers/segreg.go
  go/path_srv/internal/handlers/segreq.go
  go/path_srv/internal/handlers/segreqcore.go
  go/path_srv/internal/handlers/segreqnoncore.go
  go/path_srv/internal/handlers/segsync.go
  go/path_srv/internal/periodic/periodic.go
  go/path_srv/internal/segsyncer/segsyncer.go
  go/path_srv/main.go
Labels: PS

#1829 Refactor TopoAddr from RAI and related tests
  go/border/netconf/interface.go
  go/border/rpkt/route.go
  go/lib/addr/l4info.go
  go/lib/env/testdata/dir/topology.json
  go/lib/topology/addr.go
  go/lib/topology/addr_test.go
  go/lib/topology/doc.go
  go/lib/topology/raw.go
  go/lib/topology/strip.go
  go/lib/topology/testdata/basic.json
  go/lib/topology/testdata/core.json
  go/lib/topology/testdata/udpbr.json
  go/lib/topology/topology.go
  go/lib/topology/topology_test.go
  go/path_srv/internal/addrutil/addrutil.go
  go/path_srv/internal/handlers/testdata/topology_as1_132.json
  go/path_srv/internal/handlers/testdata/topology_as2_211.json
  go/path_srv/internal/handlers/testdata/topology_as2_222.json
  go/sciond/internal/fetcher/fetcher.go
  go/sciond/internal/servers/handlers.go
  go/sciond/server_test.go
  python/beacon_server/base.py
  python/lib/topology.py
  python/scion_elem/scion_elem.py
  python/sciond/sciond.py
  python/test/lib/topology_test.py
  python/topology/generator.py
Labels: Breaking Change

#1848 PS: Introduce messages for the new down segment sync
  doc/PathService.md
  go/lib/ctrl/path_mgmt/path_mgmt.go
  go/lib/ctrl/path_mgmt/seg_changes.go
  go/lib/infra/common.go
  go/lib/infra/messenger/messenger.go
  go/lib/infra/messenger/mock.go
  proto/path_mgmt.capnp
Labels: PS

#1851 PS: Small fixes
  go/lib/xtest/graph/graph.go
  go/path_srv/internal/handlers/common.go
  go/path_srv/internal/handlers/segreq.go
  go/path_srv/internal/handlers/segreqcore.go
Labels: PS

#1797 BR: Control/Data plane split
  go/border/gen.go
  go/border/ifid.go
  go/border/netconf/interface.go
  go/border/rctrl/ctrl.go
  go/border/rctrl/ifstate.go
  go/border/rctrl/revinfo.go
  go/border/rctx/rctx.go
  go/border/revinfo.go
  go/border/router.go
  go/border/rpkt/create.go
  go/border/rpkt/hooks.go
  go/border/rpkt/parse.go
  go/border/rpkt/path.go
  go/border/rpkt/process.go
  go/border/rpkt/route.go
  go/border/rpkt/rpkt.go
  go/border/setup.go
  go/lib/ctrl/ifid/ifid.go
  go/lib/overlay/addr.go
  go/lib/topology/addr.go
  go/lib/topology/addr_test.go
  go/lib/topology/braddr.go
  go/lib/topology/raw.go
  go/lib/topology/strip.go
  go/lib/topology/testdata/basic.json
  go/lib/topology/testdata/core.json
  go/lib/topology/testdata/udpbr.json
  go/lib/topology/topology.go
  go/lib/topology/topology_test.go
  go/path_srv/internal/addrutil/addrutil.go
  go/path_srv/internal/handlers/testdata/topology_as1_132.json
  go/path_srv/internal/handlers/testdata/topology_as2_211.json
  go/path_srv/internal/handlers/testdata/topology_as2_222.json
  go/sciond/internal/fetcher/fetcher.go
  go/sciond/internal/servers/handlers.go
  proto/ifid.capnp
  python/beacon_server/base.py
  python/lib/packet/ext_util.py
  python/lib/topology.py
  python/test/lib/topology_test.py
  python/topology/generator.py
Labels: BR, BS, Breaking Change

#1865 sciond: Remove special handling of ISD-0 request
  go/sciond/internal/fetcher/fetcher.go
Labels: sciond

#1872 sciond: Refetch path segments after some time
  go/lib/pathdb/sqlite/sqlite.go
  go/sciond/internal/fetcher/fetcher.go
  go/sciond/internal/sdconfig/sdconfig.go
  go/sciond/main.go
Labels: sciond

#1882 PS: Add missing initialization of config
  go/path_srv/internal/handlers/common.go
Labels: PS, bug

#1850 Extract common topology-related ops from Go SD and PS
  go/lib/infra/modules/itopo/itopo.go
  go/lib/infra/modules/trust/config.go
  go/lib/infra/modules/trust/trust.go
  go/lib/infra/modules/trust/trust_test.go
  go/lib/sciond/types.go
  go/lib/topology/addr.go
  go/lib/topology/topology.go
  go/lib/topology/topotestutil/topotestutil.go
  go/path_srv/internal/addrutil/addrutil.go
  go/path_srv/internal/handlers/common.go
  go/path_srv/internal/handlers/segreg.go
  go/path_srv/internal/handlers/segreqcore.go
  go/path_srv/internal/handlers/segreqnoncore.go
  go/path_srv/internal/handlers/segsync.go
  go/path_srv/internal/segsyncer/segsyncer.go
  go/path_srv/main.go
  go/sciond/internal/fetcher/fetcher.go
  go/sciond/internal/servers/handlers.go
  go/sciond/main.go
  go/sciond/server_test.go
Labels: PS, sciond

#1883 CS: Reply to newest version requests
  python/cert_server/main.py
Labels: CS

#1888 PS: Fix race condition in segsyncer, save ns in sqlite
  go/lib/pathdb/sqlite/sqlite.go
Labels: PS
