Repository scionproto/scion, pull requests merged in 2018-11, with the labels that each got.

#2086 PS: Import net/http/pprof
  go/path_srv/main.go
Labels: PS

#2088 border: unblock reader when closing a socket
  go/border/rctx/io.go
  go/lib/overlay/conn/conn.go
Labels: BR

#2091 PS: Push TRC to local CS
  go/lib/infra/modules/trust/trust.go
Labels: PS

#1994 border: best effort approach for scmp error quotes
  go/border/rpkt/l4.go
  go/border/rpkt/rpkt.go
  go/lib/scmp/pld.go
Labels: BR

#2141 CS: Introduce test suite for trustdb.TrustDB
  go/lib/infra/modules/trust/trustdb/trustdbsqlite/db_test.go
  go/lib/infra/modules/trust/trustdb/trustdbtest/testdata/ISD1-ASff00_0_311-V1.crt
  go/lib/infra/modules/trust/trustdb/trustdbtest/testdata/ISD1-V1.trc
  go/lib/infra/modules/trust/trustdb/trustdbtest/testdata/ISD2-ASff00_0_212-V1.crt
  go/lib/infra/modules/trust/trustdb/trustdbtest/testdata/ISD2-V1.trc
  go/lib/infra/modules/trust/trustdb/trustdbtest/trustdbtest.go
Labels: CS

#2114 SIG: Port to lib/env
  go/lib/addr/isdas.go
  go/lib/env/env.go
  go/lib/topology/topology.go
  go/sig/base/core/as.go
  go/sig/base/core/map.go
  go/sig/egress/router/router.go
  go/sig/internal/sigconfig/conf.go
  go/sig/internal/sigconfig/conf_test.go
  go/sig/internal/sigconfig/sample.go
  go/sig/main.go
  go/sig/metrics/metrics.go
  go/sig/sigcmn/common.go
  go/sig/xnet/xnet.go
  go/tools/scion-pki/internal/conf/isd.go
Labels: SIG

#2163 sig: Fix wrong variable captures
  go/sig/ingress/dispatcher.go
  go/sig/ingress/worker.go
Labels: SIG
