Repository scionproto/scion, pull requests merged in 2019-12, with the labels that each got.

#3441 Reliable socket dials/registrations use context.Context
  go/beacon_srv/main.go
  go/border/rctrl/ctrl.go
  go/examples/pingpong/pingpong.go
  go/godispatcher/main_test.go
  go/integration/common.go
  go/integration/end2end/main.go
  go/lib/infra/infraenv/infraenv.go
  go/lib/sciond/pathprobe/paths.go
  go/lib/sciond/sciond.go
  go/lib/snet/dispatcher.go
  go/lib/snet/snet.go
  go/lib/sock/reliable/BUILD.bazel
  go/lib/sock/reliable/mock_reliable/reliable.go
  go/lib/sock/reliable/reconnect/conn.go
  go/lib/sock/reliable/reconnect/conn_io_test.go
  go/lib/sock/reliable/reconnect/main_test.go
  go/lib/sock/reliable/reconnect/mock_reconnect/reconnect.go
  go/lib/sock/reliable/reconnect/network.go
  go/lib/sock/reliable/reconnect/network_test.go
  go/lib/sock/reliable/reconnect/reconnecter.go
  go/lib/sock/reliable/reconnect/reconnecter_test.go
  go/lib/sock/reliable/reliable.go
  go/sig/sigcmn/common.go
  go/tools/scmp/cmn/BUILD.bazel
  go/tools/scmp/cmn/common.go
  go/tools/scmp/echo/echo.go
  go/tools/scmp/main.go
  go/tools/scmp/recordpath/recordpath.go
  go/tools/scmp/traceroute/traceroute.go
  tools/gomocks
Labels: refactor

#3444 sciond: do not use snet.Addr in config
  go/sciond/internal/config/BUILD.bazel
  go/sciond/internal/config/config.go
  go/sciond/internal/config/config_test.go
  go/sciond/internal/config/sample.go
  go/sciond/main.go
  python/topology/go.py
Labels: breaking change

#3452 Fix address string for IPv6 for QUIC Infra RPC
  go/lib/infra/rpc/rpc.go
Labels: bug

#3451 Fix IPv6 registrations in godispatcher
  go/godispatcher/internal/registration/udptable.go
  go/godispatcher/internal/registration/udptable_test.go
Labels: bug

#3456 TrustStore: Sanity check resolved TRCs
  go/lib/infra/modules/trust/v2/main_test.go
  go/lib/infra/modules/trust/v2/resolver.go
  go/lib/infra/modules/trust/v2/resolver_test.go
  go/lib/infra/modules/trust/v2/testdata/gen_crypto_tar.sh
Labels: CPPKI

#3454 SPKI: Display certs in a human readable format
  go/tools/scion-pki/internal/v2/certs/BUILD.bazel
  go/tools/scion-pki/internal/v2/certs/cmd.go
  go/tools/scion-pki/internal/v2/certs/human.go
  go/tools/scion-pki/internal/v2/certs/util.go
Labels: PKI-Tool

#3493 TrustStore: Generate certificates for tests
  go/lib/infra/modules/trust/v2/testdata/gen_crypto_tar.sh
  go/tools/scion-pki/internal/v2/certs/BUILD.bazel
  go/tools/scion-pki/internal/v2/certs/loader.go
Labels: CPPKI

#3467 TrustStore: Implement sqlite database
  go/lib/infra/modules/trust/v2/db.go
  go/lib/infra/modules/trust/v2/mock_v2/v2.go
  go/lib/infra/modules/trust/v2/trustdbsqlite/BUILD.bazel
  go/lib/infra/modules/trust/v2/trustdbsqlite/db.go
  go/lib/infra/modules/trust/v2/trustdbsqlite/db_test.go
  go/lib/infra/modules/trust/v2/trustdbsqlite/schema.go
  go/lib/infra/modules/trust/v2/trustdbtest/BUILD.bazel
  go/lib/infra/modules/trust/v2/trustdbtest/testdata/ISD1-ASff00_0_110-V1.crt
  go/lib/infra/modules/trust/v2/trustdbtest/testdata/ISD1-ASff00_0_110-V10.crt
  go/lib/infra/modules/trust/v2/trustdbtest/testdata/ISD1-ASff00_0_111-V1.crt
  go/lib/infra/modules/trust/v2/trustdbtest/testdata/ISD1-V1.trc
  go/lib/infra/modules/trust/v2/trustdbtest/testdata/ISD1-V7.trc
  go/lib/infra/modules/trust/v2/trustdbtest/testdata/ISD2-V1.trc
  go/lib/infra/modules/trust/v2/trustdbtest/trustdbtest.go
Labels: CPPKI

#3502 Acceptance: Fix sig reload test
  acceptance/sig_reload_acceptance/test
  acceptance/sigutil/common.sh
  go/acceptance/sig_ping_acceptance/main.go
Labels: bug

#3506 Common: Don't panic on nil
  go/lib/common/BUILD.bazel
  go/lib/common/defs.go
  go/lib/common/defs_test.go
  go/lib/infra/BUILD.bazel
  go/lib/infra/common.go
  go/lib/infra/common_test.go
Labels: bug

#3510 TrustStore: Purge CacheOnly flag from network requests
  go/lib/infra/modules/trust/v2/export_test.go
  go/lib/infra/modules/trust/v2/handlers.go
  go/lib/infra/modules/trust/v2/provider.go
  go/lib/infra/modules/trust/v2/provider_test.go
  go/lib/infra/modules/trust/v2/resolver.go
  go/lib/infra/modules/trust/v2/rpc.go
Labels: CPPKI

#3516 TrustStore: Add signer
  go/lib/infra/modules/trust/v2/BUILD.bazel
  go/lib/infra/modules/trust/v2/main_test.go
  go/lib/infra/modules/trust/v2/mock_v2/BUILD.bazel
  go/lib/infra/modules/trust/v2/mock_v2/v2.go
  go/lib/infra/modules/trust/v2/signer.go
  go/lib/infra/modules/trust/v2/signer_test.go
  tools/gomocks
Labels: CPPKI

#3528 keyconf: Add key ring
  go/lib/keyconf/BUILD.bazel
  go/lib/keyconf/ring.go
  go/lib/keyconf/ring_test.go
Labels: CPPKI

#3530 TrustStore: The great export
  go/lib/infra/modules/trust/v2/export_test.go
  go/lib/infra/modules/trust/v2/inserter.go
  go/lib/infra/modules/trust/v2/inserter_test.go
  go/lib/infra/modules/trust/v2/inspector.go
  go/lib/infra/modules/trust/v2/inspector_test.go
  go/lib/infra/modules/trust/v2/provider.go
  go/lib/infra/modules/trust/v2/provider_test.go
  go/lib/infra/modules/trust/v2/recurser.go
  go/lib/infra/modules/trust/v2/resolver.go
  go/lib/infra/modules/trust/v2/resolver_test.go
  go/lib/infra/modules/trust/v2/router.go
  go/lib/infra/modules/trust/v2/router_test.go
  go/lib/infra/modules/trust/v2/rpc.go
Labels: CPPKI

#3538 TrustStore: Combine components to Store
  acceptance/cert_renewal_acceptance_disabled/test
  go/beacon_srv/BUILD.bazel
  go/beacon_srv/main.go
  go/cert_srv/BUILD.bazel
  go/cert_srv/internal/config/BUILD.bazel
  go/cert_srv/internal/config/state.go
  go/cert_srv/internal/config/state_test.go
  go/cert_srv/internal/reiss/BUILD.bazel
  go/cert_srv/internal/reiss/corepush.go
  go/cert_srv/internal/reiss/corepush_test.go
  go/cert_srv/internal/reiss/handler.go
  go/cert_srv/internal/reiss/requester.go
  go/cert_srv/internal/reiss/self.go
  go/cert_srv/internal/reiss/testdata/ISD1-ASff00_0_311-V1.crt
  go/cert_srv/main.go
  go/integration/cert_req/BUILD.bazel
  go/integration/cert_req/main.go
  go/lib/ctrl/cert_mgmt/BUILD.bazel
  go/lib/ctrl/cert_mgmt/chain.go
  go/lib/ctrl/cert_mgmt/trc.go
  go/lib/infra/infraenv/BUILD.bazel
  go/lib/infra/infraenv/infraenv.go
  go/lib/infra/modules/trust/v2/BUILD.bazel
  go/lib/infra/modules/trust/v2/export_test.go
  go/lib/infra/modules/trust/v2/handlers_test.go
  go/lib/infra/modules/trust/v2/recurser.go
  go/lib/infra/modules/trust/v2/store.go
  go/lib/infra/modules/trust/v2/store_test.go
  go/lib/truststorage/BUILD.bazel
  go/lib/truststorage/truststorage.go
  go/path_srv/BUILD.bazel
  go/path_srv/main.go
  go/sciond/BUILD.bazel
  go/sciond/internal/fetcher/fetcher.go
  go/sciond/main.go
  go/tools/scion-custpk-load/BUILD.bazel
  go/tools/scion-custpk-load/main.go
  python/topology/cert.py
Labels: BS, CPPKI, CS, PS, SCIOND

#3540 Add simple UDP proxy written in Go
  BUILD.bazel
  WORKSPACE
  go/tools/udpproxy/BUILD.bazel
  go/tools/udpproxy/udpproxy.go
Labels: enhancement

#3549 CPPKI: Do not double base64 encode
  go/lib/infra/modules/trust/v2/trustdbsqlite/db.go
  go/lib/infra/modules/trust/v2/trustdbtest/testdata/ISD1-ASff00_0_110-V1.crt
  go/lib/infra/modules/trust/v2/trustdbtest/testdata/ISD1-ASff00_0_110-V10.crt
  go/lib/infra/modules/trust/v2/trustdbtest/testdata/ISD1-ASff00_0_111-V1.crt
  go/lib/infra/modules/trust/v2/trustdbtest/testdata/ISD1-V1.trc
  go/lib/infra/modules/trust/v2/trustdbtest/testdata/ISD1-V2.trc
  go/lib/infra/modules/trust/v2/trustdbtest/testdata/ISD1-V3.trc
  go/lib/infra/modules/trust/v2/trustdbtest/testdata/ISD1-V7.trc
  go/lib/infra/modules/trust/v2/trustdbtest/testdata/ISD2-V1.trc
  go/lib/infra/modules/trust/v2/trustdbtest/testdata/ISD2-V2.trc
  go/lib/infra/modules/trust/v2/trustdbtest/trustdbtest.go
  go/lib/scrypto/BUILD.bazel
  go/lib/scrypto/asym.go
  go/lib/scrypto/cert/v2/as_signed.go
  go/lib/scrypto/cert/v2/as_signed_test.go
  go/lib/scrypto/cert/v2/issuer_signed.go
  go/lib/scrypto/cert/v2/issuer_signed_test.go
  go/lib/scrypto/cert/v2/verify_test.go
  go/lib/scrypto/defs.go
  go/lib/scrypto/defs_test.go
  go/lib/scrypto/trc/v2/signed.go
  go/lib/scrypto/trc/v2/signed_test.go
  go/lib/scrypto/trc/v2/verify_test.go
  go/lib/xtest/helpers.go
  go/tools/scion-pki/internal/v2/certs/cmd.go
  go/tools/scion-pki/internal/v2/certs/human.go
  go/tools/scion-pki/internal/v2/certs/testdata/ISD1/ASff00_0_110/certs/ISD1-ASff00_0_110-V1.issuer
  go/tools/scion-pki/internal/v2/certs/testdata/ISD1/ASff00_0_111/certs/ISD1-ASff00_0_111-V1.crt
  go/tools/scion-pki/internal/v2/certs/testdata/ISD1/trcs/ISD1-V1.trc
  go/tools/scion-pki/internal/v2/tmpl/topo.go
  go/tools/scion-pki/internal/v2/tmpl/topo_test.go
  go/tools/scion-pki/internal/v2/trcs/combine.go
  go/tools/scion-pki/internal/v2/trcs/human.go
  go/tools/scion-pki/internal/v2/trcs/testdata/ISD1/trcs/ISD1-V1.parts/ISD1-V1.1-ff00_0_110.sig
  go/tools/scion-pki/internal/v2/trcs/testdata/ISD1/trcs/ISD1-V1.parts/ISD1-V1.1-ff00_0_120.sig
  go/tools/scion-pki/internal/v2/trcs/testdata/ISD1/trcs/ISD1-V1.parts/ISD1-V1.1-ff00_0_130.sig
  go/tools/scion-pki/internal/v2/trcs/testdata/ISD1/trcs/ISD1-V1.parts/ISD1-V1.1-ff00_0_999.sig
  go/tools/scion-pki/internal/v2/trcs/testdata/ISD1/trcs/ISD1-V1.parts/ISD1-V1.prototype
  go/tools/scion-pki/internal/v2/trcs/testdata/ISD1/trcs/ISD1-V1.trc
  go/tools/scion-pki/internal/v2/trcs/testdata/ISD1/trcs/ISD1-V2.parts/ISD1-V2.1-ff00_0_110.sig
  go/tools/scion-pki/internal/v2/trcs/testdata/ISD1/trcs/ISD1-V2.parts/ISD1-V2.1-ff00_0_120.sig
  go/tools/scion-pki/internal/v2/trcs/testdata/ISD1/trcs/ISD1-V2.parts/ISD1-V2.prototype
  go/tools/scion-pki/internal/v2/trcs/testdata/ISD1/trcs/ISD1-V2.trc
  go/tools/scion-pki/internal/v2/trcs/testdata/ISD1/trcs/ISD1-V3.parts/ISD1-V3.1-ff00_0_120.sig
  go/tools/scion-pki/internal/v2/trcs/testdata/ISD1/trcs/ISD1-V3.parts/ISD1-V3.1-ff00_0_130.sig
  go/tools/scion-pki/internal/v2/trcs/testdata/ISD1/trcs/ISD1-V3.parts/ISD1-V3.prototype
  go/tools/scion-pki/internal/v2/trcs/testdata/ISD1/trcs/ISD1-V3.trc
  go/tools/scion-pki/internal/v2/trcs/util.go
Labels: bug

#3552 Remove overlay.OverlayAddr
  go/lib/infra/modules/itopo/testdata/topo.json
  go/lib/topology/json/json_test.go
  go/lib/topology/json/testdata/topology.json
  go/lib/topology/overlay/BUILD.bazel
  go/lib/topology/overlay/addr.go
  go/lib/topology/overlay/defs.go
  go/lib/topology/testdata/basic.json
  go/lib/topology/testdata/core.json
Labels: refactor
