Repository scionproto/scion, pull requests merged in 2019-05, with the labels that each got.

#2633 BS: Implement IfStateReq handler
  go/beacon_srv/internal/ifstate/BUILD.bazel
  go/beacon_srv/internal/ifstate/doc.go
  go/beacon_srv/internal/ifstate/handler.go
  go/beacon_srv/internal/ifstate/handler_test.go
  go/beacon_srv/internal/ifstate/revoker.go
  go/border/braccept/parser/ctrl.go
  go/lib/ctrl/path_mgmt/ifstate_infos.go
  go/lib/ctrl/path_mgmt/ifstate_req.go
Labels: BS

#2647 BS: Add topology provider
  go/beacon_srv/internal/beaconing/BUILD.bazel
  go/beacon_srv/internal/beaconing/extender.go
  go/beacon_srv/internal/beaconing/extender_config.go
  go/beacon_srv/internal/beaconing/extender_test.go
  go/beacon_srv/internal/beaconing/handler_test.go
  go/beacon_srv/internal/beaconing/originator.go
  go/beacon_srv/internal/beaconing/originator_test.go
  go/beacon_srv/internal/beaconing/propagator.go
  go/beacon_srv/internal/beaconing/propagator_test.go
  go/beacon_srv/internal/beaconing/registrar.go
  go/beacon_srv/internal/beaconing/registrar_test.go
  go/beacon_srv/internal/ifstate/handler_test.go
  go/beacon_srv/internal/ifstate/revoker.go
  go/beacon_srv/internal/ifstate/revoker_test.go
  go/beacon_srv/internal/keepalive/BUILD.bazel
  go/beacon_srv/internal/keepalive/sender.go
  go/beacon_srv/internal/keepalive/sender_test.go
  go/lib/infra/modules/itopo/itopo.go
  go/lib/topology/types.go
  go/lib/xtest/topo.go
Labels: BS

#2648 BS: Create beacon store through beaconstorage
  go/beacon_srv/internal/beacon/policy.go
  go/beacon_srv/internal/beacon/store.go
  go/beacon_srv/internal/beacon/store_test.go
  go/beacon_srv/internal/beaconstorage/config.go
Labels: BS

#2660 CS: Force cancel core pusher
  go/cert_srv/internal/reiss/corepush.go
  go/cert_srv/main.go
  go/lib/infra/modules/idiscovery/idiscovery.go
Labels: CS

#2662 BS: Filter ISD loops
  go/beacon_srv/internal/beacon/policy.go
  go/beacon_srv/internal/beacon/policy_test.go
  go/beacon_srv/internal/beacon/store.go
  go/beacon_srv/internal/beacon/testdata/policy.yml
  go/beacon_srv/internal/beacon/testdata/typedPolicy.yml
  go/beacon_srv/internal/beaconing/handler.go
  go/beacon_srv/internal/beaconing/handler_test.go
  go/beacon_srv/internal/beaconing/mock_beaconing/beaconing.go
  go/beacon_srv/internal/beaconing/propagator.go
  go/beacon_srv/internal/beaconstorage/store.go
  go/beacon_srv/main.go
Labels: BS

#2671 BS: Add metrics for beacon DB
  go/beacon_srv/internal/beacon/BUILD.bazel
  go/beacon_srv/internal/beacon/beacondbsqlite/db.go
  go/beacon_srv/internal/beacon/metrics.go
  go/beacon_srv/internal/beacon/metrics_test.go
  go/beacon_srv/internal/beaconstorage/config.go
  go/lib/infra/modules/db/BUILD.bazel
  go/lib/infra/modules/db/errors.go
  go/lib/infra/modules/db/metrics.go
  go/lib/infra/modules/db/sqler.go
Labels: BS

#2672 BS: Fast recovery
  doc/BeaconService.md
  go/beacon_srv/internal/beaconing/BUILD.bazel
  go/beacon_srv/internal/beaconing/doc.go
  go/beacon_srv/internal/beaconing/originator.go
  go/beacon_srv/internal/beaconing/propagator.go
  go/beacon_srv/internal/beaconing/propagator_test.go
  go/beacon_srv/internal/beaconing/registrar.go
  go/beacon_srv/internal/beaconing/tick.go
  go/beacon_srv/internal/ifstate/BUILD.bazel
  go/beacon_srv/internal/ifstate/ifstate.go
  go/beacon_srv/internal/ifstate/pusher.go
  go/beacon_srv/internal/ifstate/pusher_test.go
  go/beacon_srv/internal/ifstate/revoker.go
  go/beacon_srv/internal/keepalive/handler.go
  go/beacon_srv/internal/keepalive/handler_test.go
  go/beacon_srv/internal/keepalive/mock_keepalive/keepalive.go
  go/beacon_srv/main.go
  tools/gomocks
Labels: BS

#2680 BS: Load policies
  go/beacon_srv/BUILD.bazel
  go/beacon_srv/internal/config/config.go
  go/beacon_srv/internal/config/config_test.go
  go/beacon_srv/internal/config/sample.go
  go/beacon_srv/main.go
Labels: BS

#2665 BS: Reduce logging and refactor registrar/originator/propagator tasks
  go/beacon_srv/internal/beaconing/handler.go
  go/beacon_srv/internal/beaconing/originator.go
  go/beacon_srv/internal/beaconing/propagator.go
  go/beacon_srv/internal/beaconing/registrar.go
  go/beacon_srv/internal/beaconing/util.go
  go/beacon_srv/main.go
Labels: BS

#2683 BS: Add propagator/originator/registrar metrics
  go/beacon_srv/internal/beaconing/BUILD.bazel
  go/beacon_srv/internal/beaconing/metrics/BUILD.bazel
  go/beacon_srv/internal/beaconing/metrics/metrics.go
  go/beacon_srv/internal/beaconing/originator.go
  go/beacon_srv/internal/beaconing/propagator.go
  go/beacon_srv/internal/beaconing/registrar.go
  go/beacon_srv/main.go
Labels: BS

#2695 BS: Metrics about incoming beacons
  go/beacon_srv/internal/beaconing/handler.go
  go/beacon_srv/internal/beaconing/metrics/metrics.go
Labels: BS

#2694 BS: Add fast recovery unit test
  go/beacon_srv/internal/beaconing/originator_test.go
  go/beacon_srv/internal/beaconing/propagator_test.go
  go/beacon_srv/internal/beaconing/registrar_test.go
Labels: BS

#2696 disp: Fix SVC multicast and nil panic
  go/godispatcher/internal/registration/BUILD.bazel
  go/godispatcher/internal/registration/portlist.go
  go/godispatcher/internal/registration/portlist_test.go
  go/godispatcher/internal/registration/svctable_test.go
Labels: dispatcher

#2700 BS: Link adding acceptance test
  .gitignore
  acceptance/__init__.py
  acceptance/bs_add_link_acceptance/__init__.py
  acceptance/bs_add_link_acceptance/test
  acceptance/common/README.md
  acceptance/common/__init__.py
  acceptance/common/base.py
  acceptance/common/log.py
  acceptance/common/scion.py
  acceptance/common/test_scion.py
  acceptance/common/tools.py
  acceptance/flake8.ini
  scion.sh
Labels: BS

#2710 Accept: Refactor command structure
  acceptance/bs_add_link_acceptance/test
  acceptance/common/README.md
  acceptance/common/base.py
Labels: BS

#2718 sciond: Make sure maxpaths is always respected
  go/sciond/internal/fetcher/fetcher.go
Labels: sciond

#2714 BS: Start discovery runner separate from other tasks
  go/beacon_srv/main.go
Labels: BS

#2716 PS: Request core segments in parallel
  go/path_srv/internal/handlers/segreqnoncore.go
Labels: PS

#2722 PS: Do not insert next query if reply was empty
  go/path_srv/internal/handlers/common.go
  go/path_srv/internal/handlers/segreg.go
  go/path_srv/internal/handlers/segreq.go
  go/path_srv/internal/handlers/segreqnoncore_test.go
  go/path_srv/internal/handlers/segsync.go
Labels: PS

#2723 PS: Request missing TRC from core CS
  go/path_srv/internal/handlers/segreq.go
  go/path_srv/internal/handlers/segreqcore.go
  go/path_srv/internal/handlers/segreqnoncore.go
  go/path_srv/internal/handlers/segreqnoncore_test.go
Labels: PS

#2725 PS: Fix isd-local wildcard dest in non core PS
  go/beacon_srv/internal/beaconing/registrar.go
  go/lib/snet/addrutil/addrutil.go
  go/path_srv/internal/handlers/BUILD.bazel
  go/path_srv/internal/handlers/common.go
  go/path_srv/internal/handlers/segreq.go
  go/path_srv/internal/handlers/segreqcore.go
  go/path_srv/internal/handlers/segreqnoncore.go
  go/path_srv/internal/handlers/segreqnoncore_test.go
  go/path_srv/internal/segsyncer/BUILD.bazel
  go/path_srv/internal/segsyncer/segsyncer.go
  go/path_srv/main.go
Labels: PS

#2729 PS: Revocation handler should not query BR
  go/path_srv/internal/handlers/segrevoc.go
Labels: PS
