Repository scionproto/scion, pull requests merged in 2019-06, with the labels that each got.

#2742 BS: Fix killing periodic tasks
  go/beacon_srv/main.go
Labels: BS

#2750 PS: Load authoritative chain on startup
  go/beacon_srv/main.go
  go/cert_srv/setup.go
  go/lib/infra/modules/trust/config.go
  go/lib/infra/modules/trust/trust.go
  go/lib/infra/modules/trust/trust_test.go
  go/path_srv/main.go
  go/sciond/main.go
Labels: PS

#2751 sciond: Unify reply code
  go/sciond/internal/servers/handlers.go
Labels: sciond

#2757 BS: Close beacon store / db when exiting
  go/beacon_srv/internal/beacon/store.go
  go/beacon_srv/internal/beaconstorage/store.go
  go/beacon_srv/main.go
Labels: BS

#2759 BS: Reduce logging
  go/beacon_srv/internal/beaconing/originator.go
  go/beacon_srv/internal/beaconing/propagator.go
  go/beacon_srv/internal/beaconing/registrar.go
Labels: BS

#2762 PS: Return immediately if sending the reply failed
  go/path_srv/internal/handlers/segreq.go
Labels: PS

#2780 BS: Allow one hop senders reconnecting to dispatcher
  acceptance/reconnecting_acceptance/test
  go/beacon_srv/BUILD.bazel
  go/beacon_srv/main.go
  go/lib/addr/appaddr.go
Labels: BS

#2783 BR: Fix racy log
  go/border/rctx/io.go
  go/border/router.go
Labels: BR

#2790 Infra: Error out if initial sciond connect fails
  go/lib/infra/infraenv/infraenv.go
Labels: bug

#2789 BR: Fix packet leak and write on closed socket
  go/border/BUILD.bazel
  go/border/io.go
  go/border/io_test.go
  go/border/setup_test.go
  go/lib/overlay/conn/conn.go
  go/lib/overlay/conn/mock_conn/BUILD.bazel
  go/lib/overlay/conn/mock_conn/conn.go
  tools/gomocks
Labels: BR
