Repository scionproto/scion, pull requests merged in 2019-01, with the labels that each got.

#2285 PS: Change dedupe lifetime
  go/path_srv/internal/handlers/psdedupe.go
Labels: PS

#2270 Basic dataplane functionality for Go dispatcher
  go/godispatcher/internal/bufpool/buffers.go
  go/godispatcher/internal/registration/bench_test.go
  go/godispatcher/internal/registration/generators_test.go
  go/godispatcher/internal/registration/iatable.go
  go/godispatcher/internal/registration/iatable_test.go
  go/godispatcher/internal/registration/svctable_test.go
  go/godispatcher/internal/registration/table.go
  go/godispatcher/internal/registration/table_test.go
  go/godispatcher/internal/registration/udptable_test.go
  go/godispatcher/main_test.go
  go/godispatcher/network/app_socket.go
  go/godispatcher/network/defines.go
  go/godispatcher/network/dispatcher.go
  go/godispatcher/network/overlay.go
  go/lib/overlay/conn/conn.go
Labels: dispatcher

#2286 PS: Improve logging
  go/path_srv/internal/handlers/segreq.go
  go/path_srv/internal/handlers/segreqnoncore.go
Labels: PS

#2284 PS: Handle ISD-local AS-wildcard seg requests
  go/path_srv/internal/handlers/segreqnoncore.go
Labels: PS

#2298 PS: Handle error from revcache in segment filtering
  go/path_srv/internal/handlers/common.go
  go/path_srv/internal/segsyncer/segsyncer.go
Labels: PS

#2283 sciond: Handle ISD-local AS-wildcard path requests
  go/sciond/internal/fetcher/fetcher.go
Labels: sciond

#2303 Go dispatcher support for supervisord topo gen
  python/topology/config.py
  python/topology/generator.py
  python/topology/supervisor.py
Labels: dispatcher

#2301 BR: Refactor config loading
  go/border/brconf/conf.go
Labels: BR

#2305 PS: Add a test for fetchDB helper method
  go/Makefile
  go/path_srv/internal/handlers/common_test.go
Labels: PS

#2326 Go dispatcher: Add SCMP ID tracking tables
  go/godispatcher/internal/registration/iatable.go
  go/godispatcher/internal/registration/iatable_test.go
  go/godispatcher/internal/registration/scmp_table.go
  go/godispatcher/internal/registration/scmp_table_test.go
  go/godispatcher/internal/registration/table.go
Labels: dispatcher

#2332 PS: Send app level Acks for pushes
  go/lib/infra/messenger/utils.go
  go/lib/infra/modules/trust/handlers.go
  go/path_srv/internal/handlers/segreg.go
  go/path_srv/internal/handlers/segrevoc.go
  go/path_srv/internal/handlers/segsync.go
Labels: PS

#2333 Go dispatcher: Register SCMP Request IDs
  go/godispatcher/network/app_socket.go
  go/godispatcher/network/overlay.go
Labels: dispatcher

#2306 BR: Refactor socket setup
  go/border/brconf/sock.go
  go/border/rctx/io.go
  go/border/setup-posix.go
  go/border/setup.go
  go/border/setup_test.go
  go/border/testdata/topology.json
Labels: BR

#2316 BR: Transactional context setup
  acceptance/topo_br_reload_if_ip_acceptance/test
  acceptance/topo_br_reload_if_port_acceptance/test
  go/border/brconf/params.go
  go/border/brconf/sample.go
  go/border/main.go
  go/border/setup-posix.go
  go/border/setup.go
  go/border/setup_test.go
Labels: BR

#2372 Go dispatcher: SCMP ID routing takes IA into account
  go/godispatcher/internal/registration/iatable.go
  go/godispatcher/internal/registration/iatable_test.go
  go/godispatcher/internal/registration/table.go
  go/godispatcher/network/overlay.go
  go/godispatcher/network/table.go
Labels: dispatcher

#2302 braccept: revocation test and rework segment generation
  acceptance/brutil/common.sh
  acceptance/brutil/docker-compose.yml
  go/border/braccept/brA.go
  go/border/braccept/brB.go
  go/border/braccept/brC.go
  go/border/braccept/brD.go
  go/border/braccept/brtest.go
  go/border/braccept/common_tests.go
  go/border/braccept/core_brA.go
  go/border/braccept/core_brB.go
  go/border/braccept/core_brC.go
  go/border/braccept/main.go
  go/border/braccept/segments.go
  go/border/braccept/tpkt/ctrl.go
  go/border/braccept/tpkt/extensions.go
  go/border/braccept/tpkt/scmp.go
  go/border/braccept/tpkt/scnpath.go
  go/border/braccept/tpkt/tpkt.go
Labels: BR

#2388 Go dispatcher: Add metrics
  go/godispatcher/internal/metrics/metrics.go
  go/godispatcher/internal/registration/iatable.go
  go/godispatcher/internal/respool/packet.go
  go/godispatcher/main.go
  go/godispatcher/main_test.go
  go/godispatcher/network/app_socket.go
  go/godispatcher/network/overlay.go
  go/lib/addr/host.go
Labels: dispatcher
