Repository scionproto/scion, pull requests merged in 2019-08, with the labels that each got.

#2946 infra: Refactor TrustStore interface
  go/beacon_srv/main.go
  go/cert_srv/internal/reiss/handler.go
  go/cert_srv/internal/reiss/requester.go
  go/cert_srv/internal/reiss/self.go
  go/cert_srv/setup.go
  go/lib/infra/BUILD.bazel
  go/lib/infra/common.go
  go/lib/infra/infraenv/BUILD.bazel
  go/lib/infra/infraenv/infraenv.go
  go/lib/infra/messenger/messenger.go
  go/lib/infra/mock_infra/BUILD.bazel
  go/lib/infra/mock_infra/infra.go
  go/lib/infra/modules/segfetcher/BUILD.bazel
  go/lib/infra/modules/segfetcher/mock_segfetcher/BUILD.bazel
  go/lib/infra/modules/segfetcher/mock_segfetcher/segfetcher.go
  go/lib/infra/modules/segfetcher/splitter.go
  go/lib/infra/modules/segfetcher/splitter_test.go
  go/lib/infra/modules/trust/BUILD.bazel
  go/lib/infra/modules/trust/config.go
  go/lib/infra/modules/trust/handlers.go
  go/lib/infra/modules/trust/helpers.go
  go/lib/infra/modules/trust/signhelper.go
  go/lib/infra/modules/trust/trust.go
  go/lib/infra/modules/trust/trust_test.go
  go/path_srv/internal/handlers/BUILD.bazel
  go/path_srv/internal/handlers/common.go
  go/path_srv/internal/handlers/ifstateinfo.go
  go/path_srv/internal/handlers/segreq.go
  go/path_srv/internal/handlers/segreqnoncore.go
  go/path_srv/internal/handlers/segreqnoncore_test.go
  go/path_srv/internal/handlers/segrevoc.go
  go/path_srv/internal/segsyncer/BUILD.bazel
  go/path_srv/internal/segsyncer/segsyncer.go
  go/path_srv/main.go
  go/sciond/internal/fetcher/fetcher.go
  go/sciond/internal/servers/handlers.go
  go/sciond/main.go
  tools/gomocks
Labels: CPPKI

#2957 cert: Define signed AS certificate format
  go/lib/scrypto/cert/v2/BUILD.bazel
  go/lib/scrypto/cert/v2/as_signed.go
  go/lib/scrypto/cert/v2/as_signed_json_test.go
  go/lib/scrypto/cert/v2/as_signed_test.go
  go/lib/scrypto/cert/v2/base_signed.go
  go/lib/scrypto/defs.go
  go/lib/scrypto/trc/v2/signed.go
  go/lib/scrypto/trc/v2/signed_json_test.go
Labels: CPPKI

#2970 CPPKI: Use snake case
  doc/ControlPlanePKI.md
  go/lib/scrypto/cert/v2/as.go
  go/lib/scrypto/cert/v2/as_json_test.go
  go/lib/scrypto/cert/v2/as_signed.go
  go/lib/scrypto/cert/v2/as_signed_json_test.go
  go/lib/scrypto/cert/v2/base.go
  go/lib/scrypto/cert/v2/base_json_test.go
  go/lib/scrypto/cert/v2/issuer.go
  go/lib/scrypto/cert/v2/issuer_json_test.go
  go/lib/scrypto/cert/v2/issuer_signed.go
  go/lib/scrypto/cert/v2/issuer_signed_json_test.go
  go/lib/scrypto/keymeta.go
  go/lib/scrypto/keymeta_test.go
  go/lib/scrypto/trc/v2/keychanges.go
  go/lib/scrypto/trc/v2/pop.go
  go/lib/scrypto/trc/v2/primary.go
  go/lib/scrypto/trc/v2/primary_json_test.go
  go/lib/scrypto/trc/v2/signed.go
  go/lib/scrypto/trc/v2/signed_json_test.go
  go/lib/scrypto/trc/v2/trc.go
  go/lib/scrypto/trc/v2/trc_json_test.go
  go/lib/scrypto/trc/v2/trc_test.go
  go/lib/scrypto/trc/v2/update.go
  go/lib/scrypto/trc/v2/update_test.go
  go/lib/scrypto/trc/v2/verify.go
  go/lib/scrypto/trc/v2/verify_test.go
  go/lib/scrypto/validity.go
  go/lib/scrypto/validity_test.go
Labels: CPPKI

#2974 BR: Move Hop Field Mac Pool to the Context
  acceptance/brutil/common.sh
  acceptance/brutil/docker-compose.yml
  go/beacon_srv/BUILD.bazel
  go/beacon_srv/main.go
  go/border/braccept/shared/BUILD.bazel
  go/border/braccept/shared/init.go
  go/border/brconf/BUILD.bazel
  go/border/brconf/conf.go
  go/border/rctx/BUILD.bazel
  go/border/rctx/rctx.go
  go/border/rpkt/extn_onehoppath.go
  go/border/rpkt/path.go
  go/border/setup.go
  go/lib/scrypto/BUILD.bazel
  go/lib/scrypto/mac.go
Labels: BR

#2972 BS: Max MaxExpTime configurable
  go/beacon_srv/BUILD.bazel
  go/beacon_srv/internal/beacon/BUILD.bazel
  go/beacon_srv/internal/beacon/policy.go
  go/beacon_srv/internal/beacon/policy_test.go
  go/beacon_srv/internal/beacon/store.go
  go/beacon_srv/internal/beacon/testdata/policy.yml
  go/beacon_srv/internal/beacon/testdata/typedPolicy.yml
  go/beacon_srv/internal/beaconing/extender.go
  go/beacon_srv/internal/beaconing/extender_config.go
  go/beacon_srv/internal/beaconing/extender_test.go
  go/beacon_srv/internal/beaconing/originator_test.go
  go/beacon_srv/internal/beaconing/propagator_test.go
  go/beacon_srv/internal/beaconing/registrar_test.go
  go/beacon_srv/internal/beaconstorage/BUILD.bazel
  go/beacon_srv/internal/beaconstorage/store.go
  go/beacon_srv/internal/config/sample.go
  go/beacon_srv/main.go
Labels: BS

#2980 cert: Define certificate chain structure
  go/lib/scrypto/cert/v2/BUILD.bazel
  go/lib/scrypto/cert/v2/as.go
  go/lib/scrypto/cert/v2/as_test.go
  go/lib/scrypto/cert/v2/chain.go
  go/lib/scrypto/cert/v2/chain_json_test.go
  go/lib/scrypto/cert/v2/verify.go
  go/lib/scrypto/cert/v2/verify_test.go
  go/lib/scrypto/validity.go
  go/lib/scrypto/validity_test.go
Labels: CPPKI

#2991 SPKI: Generate templates
  go/tools/scion-pki/internal/cmd/BUILD.bazel
  go/tools/scion-pki/internal/cmd/cmd.go
  go/tools/scion-pki/internal/pkicmn/pkicmn.go
  go/tools/scion-pki/internal/v2/cmd/BUILD.bazel
  go/tools/scion-pki/internal/v2/cmd/cmd.go
  go/tools/scion-pki/internal/v2/conf/BUILD.bazel
  go/tools/scion-pki/internal/v2/conf/as.go
  go/tools/scion-pki/internal/v2/conf/as_test.go
  go/tools/scion-pki/internal/v2/conf/isd.go
  go/tools/scion-pki/internal/v2/conf/isd_test.go
  go/tools/scion-pki/internal/v2/tmpl/BUILD.bazel
  go/tools/scion-pki/internal/v2/tmpl/as.go
  go/tools/scion-pki/internal/v2/tmpl/cmd.go
  go/tools/scion-pki/internal/v2/tmpl/isd.go
Labels: CPPKI, scion-pki

#3027 BS: Display version
  go/beacon_srv/BUILD.bazel
Labels: BS

#3008 TRC: Add proof of possession verifier
  go/lib/scrypto/trc/v2/verify.go
  go/lib/scrypto/trc/v2/verify_test.go
Labels: CPPKI

#3004 SPKI: Generate keys
  go/lib/keyconf/keyconf.go
  go/tools/scion-pki/internal/v2/cmd/BUILD.bazel
  go/tools/scion-pki/internal/v2/cmd/cmd.go
  go/tools/scion-pki/internal/v2/conf/as.go
  go/tools/scion-pki/internal/v2/keys/BUILD.bazel
  go/tools/scion-pki/internal/v2/keys/cmd.go
  go/tools/scion-pki/internal/v2/keys/gen.go
Labels: CPPKI, PKI-Tool

#3011 HP: Implement GroupId -> Registry config lookup
  go/beacon_srv/internal/beacon/hp_policy_test.go
  go/hidden_path_srv/internal/hpsegreq/BUILD.bazel
  go/hidden_path_srv/internal/hpsegreq/registry_algo.go
  go/hidden_path_srv/internal/hpsegreq/registry_algo_test.go
  go/lib/hiddenpath/group.go
Labels: HP

#3047 sciond: Fix bug with new error reporting
  go/sciond/internal/fetcher/fetcher.go
Labels: SCIOND, bug

#3044 HP: HiddenPathDB interface and PathDB Adapter
  go/hidden_path_srv/internal/hiddenpathdb/BUILD.bazel
  go/hidden_path_srv/internal/hiddenpathdb/adapter/BUILD.bazel
  go/hidden_path_srv/internal/hiddenpathdb/adapter/pathdb_adapter.go
  go/hidden_path_srv/internal/hiddenpathdb/adapter/pathdb_adapter_test.go
  go/hidden_path_srv/internal/hiddenpathdb/hiddenpathdb.go
  go/lib/xtest/matchers/matchers.go
Labels: HP

#2997 PS,SD: Use new path lookup strategy
  acceptance/reconnecting_acceptance/test
  acceptance/topo_ps_reloads_br_acceptance/test
  go/lib/infra/messenger/addr.go
  go/lib/infra/modules/segfetcher/fetcher.go
  go/path_srv/BUILD.bazel
  go/path_srv/internal/handlers/BUILD.bazel
  go/path_srv/internal/handlers/common_test.go
  go/path_srv/internal/handlers/psdedupe.go
  go/path_srv/internal/handlers/segreq.go
  go/path_srv/internal/handlers/segreqcore.go
  go/path_srv/internal/handlers/segreqnoncore.go
  go/path_srv/internal/handlers/segreqnoncore_test.go
  go/path_srv/internal/handlers/segrevoc.go
  go/path_srv/main.go
  go/sciond/BUILD.bazel
  go/sciond/internal/fetcher/BUILD.bazel
  go/sciond/internal/fetcher/fetcher.go
  go/sciond/internal/servers/BUILD.bazel
  go/sciond/internal/servers/handlers.go
  go/sciond/main.go
Labels: PS, SCIOND, breaking change

#3049 SPKI: Generate prototype TRC
  go/lib/scrypto/asym.go
  go/tools/scion-pki/internal/pkicmn/pkicmn.go
  go/tools/scion-pki/internal/v2/cmd/BUILD.bazel
  go/tools/scion-pki/internal/v2/cmd/cmd.go
  go/tools/scion-pki/internal/v2/conf/isd.go
  go/tools/scion-pki/internal/v2/keys/gen.go
  go/tools/scion-pki/internal/v2/trc/BUILD.bazel
  go/tools/scion-pki/internal/v2/trc/ases.go
  go/tools/scion-pki/internal/v2/trc/cmd.go
  go/tools/scion-pki/internal/v2/trc/prototype.go
  go/tools/scion-pki/internal/v2/trc/util.go
Labels: CPPKI, PKI-Tool

#3058 PS,SD: Use revocations from SegReply to invalidate NextQuery
  go/lib/infra/modules/segfetcher/fetcher.go
  go/lib/infra/modules/segfetcher/revocation.go
  go/lib/infra/modules/segfetcher/segreplyhandler.go
  go/lib/infra/modules/segfetcher/segreplyhandler_test.go
Labels: PS, SCIOND

#3059 proto: Re-enable catching panics in proto library
  go/proto/cereal.go
  go/proto/cereal_test.go
Labels: bug

#3056 SPKI: Generate TRC signatures
  go/tools/scion-pki/internal/pkicmn/pkicmn.go
  go/tools/scion-pki/internal/v2/trc/BUILD.bazel
  go/tools/scion-pki/internal/v2/trc/cmd.go
  go/tools/scion-pki/internal/v2/trc/sign.go
  go/tools/scion-pki/internal/v2/trc/util.go
Labels: CPPKI, PKI-Tool
