Repository scionproto/scion, pull requests merged in 2019-09, with the labels that each got.

#3068 SPKI: Display human readable TRCs
  go/tools/scion-pki/internal/v2/trc/BUILD.bazel
  go/tools/scion-pki/internal/v2/trc/cmd.go
  go/tools/scion-pki/internal/v2/trc/human.go
Labels: CPPKI, PKI-Tool

#2932 CPPKI: Emphasize best-effort revocation + CAP trade-off
  doc/ControlPlanePKI.md
Labels: CPPKI, documentation

#3074 Disp: Do not allow running as root
  go/border/main.go
  go/godispatcher/BUILD.bazel
  go/godispatcher/main.go
  go/sig/main.go
Labels: Dispatcher, enhancement

#3018 SIG: Tighten the API between main and ingress/egress
  go/sig/BUILD.bazel
  go/sig/egress/BUILD.bazel
  go/sig/egress/api.go
  go/sig/ingress/BUILD.bazel
  go/sig/ingress/api.go
  go/sig/main.go
Labels: SIG, refactor

#3079 SPKI: Generate templates from topology file
  go/tools/scion-pki/internal/certs/gen.go
  go/tools/scion-pki/internal/tmpl/BUILD.bazel
  go/tools/scion-pki/internal/tmpl/cmd.go
  go/tools/scion-pki/internal/tmpl/topo.go
  go/tools/scion-pki/internal/v2/cmd/cmd.go
  go/tools/scion-pki/internal/v2/tmpl/BUILD.bazel
  go/tools/scion-pki/internal/v2/tmpl/as.go
  go/tools/scion-pki/internal/v2/tmpl/cmd.go
  go/tools/scion-pki/internal/v2/tmpl/topo.go
Labels: CPPKI, PKI-Tool, enhancement

#3072 Add method to filter segments with a path policy
  go/lib/pathmgr/pathmgr.go
  go/lib/pathpol/pathset.go
  go/lib/pathpol/policy_test.go
  go/path_srv/internal/segutil/BUILD.bazel
  go/path_srv/internal/segutil/filter.go
  go/path_srv/internal/segutil/filter_test.go
  go/sciond/internal/fetcher/filter.go
Labels: enhancement

#3085 Acceptance: Add SIG test with short-lived segments
  acceptance/sig_ping_acceptance/test
  acceptance/sig_short_exp_time_acceptance/test
Labels: SIG, enhancement

#3084 generator: Use scion-pki tool
  acceptance/cert_renewal_acceptance/test
  go/tools/scion-pki/internal/certs/BUILD.bazel
  go/tools/scion-pki/internal/certs/cmd.go
  go/tools/scion-pki/internal/certs/customers.go
  python/topology/cert.py
  python/topology/config.py
Labels: PKI-Tool, enhancement

#3064 Avoid cgo in lib/overlay/conn to simplify cross-compilation
  go/godispatcher/network/dispatcher.go
  go/lib/overlay/conn/BUILD.bazel
  go/lib/overlay/conn/c.go
  go/lib/overlay/conn/conn.go
Labels: enhancement, needs investigation

#3092 PS: Log & return err from segfetcher
  go/path_srv/internal/segreq/BUILD.bazel
  go/path_srv/internal/segreq/handler.go
Labels: PS

#3099 sciond socket file mode.
  go/lib/sciond/sciond.go
  go/sciond/internal/config/config.go
  go/sciond/internal/config/config_test.go
  go/sciond/internal/config/sample.go
  go/sciond/internal/servers/server.go
  go/sciond/main.go
Labels: SCIOND

#3105 BS: Make ifstate metric useful
  go/beacon_srv/internal/ifstate/metrics.go
Labels: BS, monitoring

#3111 Configurable RevConfig
  go/beacon_srv/internal/config/BUILD.bazel
  go/beacon_srv/internal/config/config.go
  go/beacon_srv/internal/config/config_test.go
  go/beacon_srv/internal/config/sample.go
  go/beacon_srv/internal/ifstate/revoker.go
  go/beacon_srv/internal/ifstate/revoker_test.go
  go/beacon_srv/internal/revocation/handler_test.go
  go/beacon_srv/main.go
Labels: enhancement

#3075 HP: Add HPSegRegHandler
  go/hidden_path_srv/internal/hiddenpathdb/BUILD.bazel
  go/hidden_path_srv/internal/hiddenpathdb/adapter/BUILD.bazel
  go/hidden_path_srv/internal/hiddenpathdb/adapter/pathdb_adapter.go
  go/hidden_path_srv/internal/hiddenpathdb/adapter/pathdb_adapter_test.go
  go/hidden_path_srv/internal/hiddenpathdb/hiddenpathdb.go
  go/hidden_path_srv/internal/hpsegreq/registry_algo.go
  go/hidden_path_srv/internal/hpsegreq/registry_algo_test.go
  go/hidden_path_srv/internal/registration/BUILD.bazel
  go/hidden_path_srv/internal/registration/handler.go
  go/hidden_path_srv/internal/registration/validator.go
  go/hidden_path_srv/internal/registration/validator_test.go
  go/lib/ctrl/path_mgmt/hp_cfg.go
  go/lib/ctrl/seg/hiddenpath_extn.go
  go/lib/hiddenpath/group.go
  go/lib/hiddenpath/group_test.go
  go/lib/infra/modules/seghandler/seghandler.go
  go/path_srv/internal/handlers/segreg.go
Labels: HP, enhancement

#3123 HP: Registration Handler tests
  go/hidden_path_srv/internal/registration/BUILD.bazel
  go/hidden_path_srv/internal/registration/handler.go
  go/hidden_path_srv/internal/registration/handler_test.go
  go/hidden_path_srv/internal/registration/mock_registration/BUILD.bazel
  go/hidden_path_srv/internal/registration/mock_registration/registration.go
  tools/gomocks
Labels: HP, enhancement

#3102 SPKI: Use RunE in cobra commands
  go/lib/keyconf/keyconf.go
  go/tools/scion-pki/internal/cmd/BUILD.bazel
  go/tools/scion-pki/internal/cmd/cmd.go
  go/tools/scion-pki/internal/v2/cmd/BUILD.bazel
  go/tools/scion-pki/internal/v2/cmd/cmd.go
  go/tools/scion-pki/internal/v2/conf/as.go
  go/tools/scion-pki/internal/v2/conf/isd.go
  go/tools/scion-pki/internal/v2/keys/cmd.go
  go/tools/scion-pki/internal/v2/keys/gen.go
  go/tools/scion-pki/internal/v2/tmpl/as.go
  go/tools/scion-pki/internal/v2/tmpl/cmd.go
  go/tools/scion-pki/internal/v2/tmpl/isd.go
  go/tools/scion-pki/internal/v2/tmpl/topo.go
  go/tools/scion-pki/internal/v2/trcs/BUILD.bazel
  go/tools/scion-pki/internal/v2/trcs/ases.go
  go/tools/scion-pki/internal/v2/trcs/cmd.go
  go/tools/scion-pki/internal/v2/trcs/human.go
  go/tools/scion-pki/internal/v2/trcs/prototype.go
  go/tools/scion-pki/internal/v2/trcs/sign.go
  go/tools/scion-pki/internal/v2/trcs/util.go
Labels: PKI-Tool, enhancement

#3128 Update jaeger all-in-one image to 1.14
  python/topology/jaeger.py
Labels: enhancement

#3131 jaeger: Fix storing segments
  python/topology/jaeger.py
  scion.sh
Labels: enhancement

#3134 snet: Use correct base conn
  go/lib/snet/conn.go
Labels: SNET

#3161 prom: Remove custom registry
  go/beacon_srv/BUILD.bazel
  go/beacon_srv/internal/metrics/BUILD.bazel
  go/beacon_srv/internal/metrics/metrics.go
  go/beacon_srv/main.go
  go/border/BUILD.bazel
  go/border/main.go
  go/border/metrics/metrics.go
  go/border/router.go
  go/border/setup_test.go
  go/cert_srv/BUILD.bazel
  go/cert_srv/internal/metrics/BUILD.bazel
  go/cert_srv/internal/metrics/metrics.go
  go/cert_srv/setup.go
  go/godispatcher/BUILD.bazel
  go/godispatcher/internal/metrics/metrics.go
  go/godispatcher/main.go
  go/godispatcher/main_test.go
  go/lib/infra/messenger/metrics.go
  go/lib/infra/metrics.go
  go/lib/infra/modules/db/metrics.go
  go/lib/prom/prom.go
  go/path_srv/BUILD.bazel
  go/path_srv/internal/metrics/BUILD.bazel
  go/path_srv/internal/metrics/metrics.go
  go/path_srv/main.go
  go/sciond/BUILD.bazel
  go/sciond/internal/metrics/BUILD.bazel
  go/sciond/internal/metrics/metrics.go
  go/sciond/main.go
  go/sig/BUILD.bazel
  go/sig/egress/worker/BUILD.bazel
  go/sig/egress/worker/worker_test.go
  go/sig/ingress/BUILD.bazel
  go/sig/ingress/worker_test.go
  go/sig/main.go
  go/sig/metrics/metrics.go
Labels: breaking change

#3150 mock: Generate mocks for matched packages
  tools/gomocks
Labels: enhancement

#3171 SegVerifier: Set TRC version on verifier
  go/lib/infra/modules/segverifier/segverifier.go
Labels: bug

#3162 doc: Add metrics doc
  doc/Metrics.md
Labels: monitoring

#3169 TrustStore: Add metrics
  go/beacon_srv/main.go
  go/cert_srv/setup.go
  go/lib/infra/modules/db/metrics.go
  go/lib/infra/modules/trust/BUILD.bazel
  go/lib/infra/modules/trust/handlers.go
  go/lib/infra/modules/trust/internal/metrics/BUILD.bazel
  go/lib/infra/modules/trust/internal/metrics/context.go
  go/lib/infra/modules/trust/internal/metrics/db.go
  go/lib/infra/modules/trust/internal/metrics/handler.go
  go/lib/infra/modules/trust/internal/metrics/labels_test.go
  go/lib/infra/modules/trust/internal/metrics/metrics.go
  go/lib/infra/modules/trust/internal/metrics/store.go
  go/lib/infra/modules/trust/signhelper.go
  go/lib/infra/modules/trust/trust.go
  go/lib/infra/modules/trust/trustdb/BUILD.bazel
  go/lib/infra/modules/trust/trustdb/metrics.go
  go/lib/prom/prom.go
  go/path_srv/main.go
Labels: monitoring

#3179 Remove goconvey from config tests
  go/beacon_srv/internal/beaconstorage/beaconstoragetest/BUILD.bazel
  go/beacon_srv/internal/beaconstorage/beaconstoragetest/config.go
  go/beacon_srv/internal/beaconstorage/beaconstoragetest/config_test.go
  go/beacon_srv/internal/config/BUILD.bazel
  go/beacon_srv/internal/config/config_test.go
  go/border/brconf/BUILD.bazel
  go/border/brconf/params_test.go
  go/cert_srv/internal/config/BUILD.bazel
  go/cert_srv/internal/config/config_test.go
  go/godispatcher/internal/config/BUILD.bazel
  go/godispatcher/internal/config/config_test.go
  go/lib/env/envtest/BUILD.bazel
  go/lib/env/envtest/config.go
  go/lib/env/envtest/config_test.go
  go/lib/infra/modules/idiscovery/idiscoverytest/BUILD.bazel
  go/lib/infra/modules/idiscovery/idiscoverytest/config.go
  go/lib/infra/modules/idiscovery/idiscoverytest/config_test.go
  go/lib/pathstorage/pathstoragetest/BUILD.bazel
  go/lib/pathstorage/pathstoragetest/config.go
  go/lib/pathstorage/pathstoragetest/config_test.go
  go/lib/truststorage/truststoragetest/BUILD.bazel
  go/lib/truststorage/truststoragetest/config.go
  go/lib/truststorage/truststoragetest/config_test.go
  go/path_srv/internal/config/BUILD.bazel
  go/path_srv/internal/config/config_test.go
  go/sciond/internal/config/BUILD.bazel
  go/sciond/internal/config/config_test.go
  go/sig/internal/sigconfig/BUILD.bazel
  go/sig/internal/sigconfig/conf_test.go
Labels: refactor

#3174 TrustStore: Define components
  go/lib/infra/modules/trust/v2/BUILD.bazel
  go/lib/infra/modules/trust/v2/db.go
  go/lib/infra/modules/trust/v2/inserter.go
  go/lib/infra/modules/trust/v2/inspector.go
  go/lib/infra/modules/trust/v2/internal/decoded/BUILD.bazel
  go/lib/infra/modules/trust/v2/internal/decoded/decode.go
  go/lib/infra/modules/trust/v2/main_test.go
  go/lib/infra/modules/trust/v2/provider.go
  go/lib/infra/modules/trust/v2/recurser.go
  go/lib/infra/modules/trust/v2/resolvers.go
  go/lib/infra/modules/trust/v2/router.go
  go/lib/infra/modules/trust/v2/rpc.go
  go/lib/infra/modules/trust/v2/testdata/.gitignore
  go/lib/infra/modules/trust/v2/testdata/BUILD.bazel
  go/lib/infra/modules/trust/v2/testdata/gen_crypto_tar.sh
  go/lib/scrypto/trc/v2/signed.go
Labels: CPPKI

#3181 discovery: Add metrics for itopo and idiscovery
  go/lib/infra/modules/idiscovery/BUILD.bazel
  go/lib/infra/modules/idiscovery/idiscovery.go
  go/lib/infra/modules/idiscovery/internal/metrics/BUILD.bazel
  go/lib/infra/modules/idiscovery/internal/metrics/metrics.go
  go/lib/infra/modules/itopo/BUILD.bazel
  go/lib/infra/modules/itopo/cleaner.go
  go/lib/infra/modules/itopo/internal/metrics/BUILD.bazel
  go/lib/infra/modules/itopo/internal/metrics/metrics.go
  go/lib/infra/modules/itopo/itopo.go
Labels: monitoring

#3189 discovery: Call correct callback when cleaning dynamic
  go/lib/infra/modules/itopo/cleaner.go
  go/lib/infra/modules/itopo/itopo.go
Labels: bug
