Repository scionproto/scion, pull requests merged in 2019-11, with the labels that each got.

#3305 Minimized interface argument needed to create default SCMP handler
  go/lib/snet/dispatcher.go
  go/lib/snet/snet.go
Labels: refactor

#3228 SPKI: Add TRC configuration
  go/tools/scion-pki/internal/v2/conf/BUILD.bazel
  go/tools/scion-pki/internal/v2/conf/testdata/BUILD.bazel
  go/tools/scion-pki/internal/v2/conf/testdata/trc-v1.toml
  go/tools/scion-pki/internal/v2/conf/testdata/trc-v2.toml
  go/tools/scion-pki/internal/v2/conf/testdata/trc.go
  go/tools/scion-pki/internal/v2/conf/trc.go
  go/tools/scion-pki/internal/v2/conf/trc_test.go
Labels: CPPKI, PKI-Tool

#3300 SIG: Move xnet to internal
  go/sig/BUILD.bazel
  go/sig/internal/xnet/BUILD.bazel
  go/sig/internal/xnet/xnet.go
  go/sig/main.go
Labels: refactor

#3308 SPKI: Add key commands
  go/tools/scion-pki/internal/v2/keys/cmd.go
  go/tools/scion-pki/internal/v2/keys/pub.go
Labels: PKI-Tool

#3316 Refactor: split pathpol tests into multiple files
  go/lib/pathpol/BUILD.bazel
  go/lib/pathpol/acl_test.go
  go/lib/pathpol/policy_test.go
  go/lib/pathpol/sequence_test.go
Labels: refactor

#3311 TrustStore: Disable unit tests
  go/lib/infra/modules/trust/v2/inserter_test.go
  go/lib/infra/modules/trust/v2/inspector_test.go
  go/lib/infra/modules/trust/v2/provider_test.go
  go/lib/infra/modules/trust/v2/recurser_test.go
  go/lib/infra/modules/trust/v2/resolver_test.go
  go/lib/infra/modules/trust/v2/router_test.go
  go/lib/infra/modules/trust/v2/testdata/gen_crypto_tar.sh
Labels: PKI-Tool

#3320 Export types of Topology fields
  go/lib/topology/topology.go
Labels: refactor

#3323 Remove addr.L4Info
  go/beacon_srv/internal/beaconing/originator_test.go
  go/beacon_srv/internal/beaconing/propagator_test.go
  go/beacon_srv/internal/keepalive/sender_test.go
  go/beacon_srv/internal/onehop/sender.go
  go/beacon_srv/internal/onehop/sender_test.go
  go/beacon_srv/main.go
  go/border/io.go
  go/border/io_test.go
  go/border/rctrl/ifstate.go
  go/border/rctrl/revinfo.go
  go/border/rpkt/route.go
  go/examples/discovery_client/client.go
  go/examples/pingpong/pingpong.go
  go/godispatcher/main_test.go
  go/godispatcher/network/app_socket.go
  go/godispatcher/network/dispatcher.go
  go/integration/cert_req/main.go
  go/integration/common.go
  go/integration/end2end/main.go
  go/lib/addr/BUILD.bazel
  go/lib/addr/appaddr.go
  go/lib/addr/l4info.go
  go/lib/addr/util.go
  go/lib/discovery/discovery.go
  go/lib/discovery/discoverypool/pool_test.go
  go/lib/healthpool/svcinstance/pool_test.go
  go/lib/hostinfo/hostinfo.go
  go/lib/infra/infraenv/infraenv.go
  go/lib/infra/messenger/addr.go
  go/lib/infra/messenger/addr_test.go
  go/lib/infra/rpc/rpc.go
  go/lib/overlay/addr.go
  go/lib/overlay/conn/conn.go
  go/lib/sciond/pathprobe/paths.go
  go/lib/snet/addr.go
  go/lib/snet/addr_test.go
  go/lib/snet/reader.go
  go/lib/snet/router.go
  go/lib/snet/router_test.go
  go/lib/snet/snet.go
  go/lib/snet/writer.go
  go/lib/snet/writer_test.go
  go/lib/sock/reliable/reconnect/main_test.go
  go/lib/sock/reliable/reconnect/network.go
  go/lib/sock/reliable/reconnect/network_test.go
  go/lib/sock/reliable/reliable.go
  go/lib/svc/svc_test.go
  go/lib/topology/addr.go
  go/lib/topology/addr_test.go
  go/lib/topology/raw.go
  go/lib/topology/topology.go
  go/lib/topology/topology_test.go
  go/sciond/internal/config/config_test.go
  go/sig/base/pollhdlr.go
  go/sig/egress/siginfo/sig.go
  go/sig/sigcmn/common.go
  go/tools/scmp/cmn/BUILD.bazel
  go/tools/scmp/cmn/common.go
Labels: refactor

#3319 SPKI: Generate TRC and keys config for topo
  go/lib/scrypto/trc/v2/primary.go
  go/tools/scion-pki/internal/v2/conf/testdata/trc-v1.toml
  go/tools/scion-pki/internal/v2/conf/testdata/trc.go
  go/tools/scion-pki/internal/v2/conf/trc.go
  go/tools/scion-pki/internal/v2/tmpl/BUILD.bazel
  go/tools/scion-pki/internal/v2/tmpl/as.go
  go/tools/scion-pki/internal/v2/tmpl/cmd.go
  go/tools/scion-pki/internal/v2/tmpl/isd.go
  go/tools/scion-pki/internal/v2/tmpl/keys.go
  go/tools/scion-pki/internal/v2/tmpl/topo.go
  go/tools/scion-pki/internal/v2/tmpl/topo_test.go
Labels: PKI-Tool

#3330 Convert more goconvey tests to normal go tests
  go/godispatcher/network/BUILD.bazel
  go/godispatcher/network/overlay_test.go
  go/hidden_path_srv/internal/hpsegreq/BUILD.bazel
  go/hidden_path_srv/internal/hpsegreq/fetcher_test.go
  go/hidden_path_srv/internal/registration/BUILD.bazel
  go/hidden_path_srv/internal/registration/validator_test.go
  go/lib/infra/BUILD.bazel
  go/lib/infra/common_test.go
  go/lib/infra/modules/trust/v2/router_test.go
  go/lib/infra/rpc/BUILD.bazel
  go/lib/infra/rpc/rpc_test.go
  go/lib/l4/BUILD.bazel
  go/lib/l4/udp_test.go
  go/lib/pathpol/BUILD.bazel
  go/lib/pathpol/acl_test.go
  go/lib/scrypto/asym_test.go
  go/lib/scrypto/cert/v2/BUILD.bazel
  go/lib/scrypto/cert/v2/as_test.go
  go/lib/scrypto/cert/v2/base_test.go
  go/lib/scrypto/cert/v2/issuer_test.go
  go/lib/scrypto/trc/v2/BUILD.bazel
  go/lib/scrypto/trc/v2/primary_test.go
  go/lib/scrypto/trc/v2/trc_test.go
  go/lib/scrypto/trc/v2/update_test.go
  go/lib/serrors/BUILD.bazel
  go/lib/serrors/errors_test.go
  go/lib/sock/reliable/BUILD.bazel
  go/lib/sock/reliable/errors.go
  go/lib/sock/reliable/frame_test.go
  go/lib/sock/reliable/packetizer_test.go
  go/lib/sock/reliable/registration_test.go
  go/lib/spath/BUILD.bazel
  go/lib/spath/hop_test.go
  go/lib/svc/BUILD.bazel
  go/lib/svc/messages_test.go
  go/lib/topology/BUILD.bazel
  go/lib/topology/addr_test.go
  go/lib/topology/topology_test.go
  go/lib/xtest/BUILD.bazel
  go/lib/xtest/convey.go
  go/lib/xtest/graphupdater/BUILD.bazel
  go/lib/xtest/graphupdater/main_test.go
  go/sig/config/BUILD.bazel
  go/sig/config/config_test.go
  go/tools/scion-pki/internal/pkicmn/BUILD.bazel
  go/tools/scion-pki/internal/pkicmn/pkicmn_test.go
  go/tools/scion-pki/internal/v2/conf/BUILD.bazel
  go/tools/scion-pki/internal/v2/conf/as_test.go
Labels: refactor

#3331 SPKI: Remove legacy key generation
  go/tools/scion-pki/internal/v2/keys/BUILD.bazel
  go/tools/scion-pki/internal/v2/keys/cmd.go
  go/tools/scion-pki/internal/v2/keys/gen.go
  go/tools/scion-pki/internal/v2/keys/priv.go
Labels: PKI-Tool

#3328 SPKI: Prototype TRC generation
  go/lib/scrypto/asym.go
  go/lib/scrypto/trc/v2/signed.go
  go/lib/scrypto/trc/v2/update.go
  go/tools/scion-pki/internal/pkicmn/pkicmn.go
  go/tools/scion-pki/internal/pkicmn/pkicmn_test.go
  go/tools/scion-pki/internal/v2/conf/trc.go
  go/tools/scion-pki/internal/v2/keys/priv.go
  go/tools/scion-pki/internal/v2/keys/pub.go
  go/tools/scion-pki/internal/v2/trcs/BUILD.bazel
  go/tools/scion-pki/internal/v2/trcs/ases.go
  go/tools/scion-pki/internal/v2/trcs/cmd.go
  go/tools/scion-pki/internal/v2/trcs/combine.go
  go/tools/scion-pki/internal/v2/trcs/gen.go
  go/tools/scion-pki/internal/v2/trcs/human.go
  go/tools/scion-pki/internal/v2/trcs/loader.go
  go/tools/scion-pki/internal/v2/trcs/prototype.go
  go/tools/scion-pki/internal/v2/trcs/prototype_test.go
  go/tools/scion-pki/internal/v2/trcs/sign.go
  go/tools/scion-pki/internal/v2/trcs/testdata/ISD1/ASff00_0_110/keys.toml
  go/tools/scion-pki/internal/v2/trcs/testdata/ISD1/ASff00_0_110/keys/trc-issuing-v1.key
  go/tools/scion-pki/internal/v2/trcs/testdata/ISD1/ASff00_0_110/keys/trc-voting-offline-v1.key
  go/tools/scion-pki/internal/v2/trcs/testdata/ISD1/ASff00_0_110/keys/trc-voting-online-v1.key
  go/tools/scion-pki/internal/v2/trcs/testdata/ISD1/ASff00_0_110/keys/trc-voting-online-v2.key
  go/tools/scion-pki/internal/v2/trcs/testdata/ISD1/ASff00_0_120/keys.toml
  go/tools/scion-pki/internal/v2/trcs/testdata/ISD1/ASff00_0_120/keys/trc-voting-offline-v1.key
  go/tools/scion-pki/internal/v2/trcs/testdata/ISD1/ASff00_0_120/keys/trc-voting-online-v1.key
  go/tools/scion-pki/internal/v2/trcs/testdata/ISD1/ASff00_0_130/keys.toml
  go/tools/scion-pki/internal/v2/trcs/testdata/ISD1/ASff00_0_130/keys/trc-issuing-v1.key
  go/tools/scion-pki/internal/v2/trcs/testdata/ISD1/ASff00_0_130/keys/trc-voting-offline-v1.key
  go/tools/scion-pki/internal/v2/trcs/testdata/ISD1/ASff00_0_130/keys/trc-voting-online-v1.key
  go/tools/scion-pki/internal/v2/trcs/testdata/ISD1/trc-v1.toml
  go/tools/scion-pki/internal/v2/trcs/testdata/ISD1/trc-v2.toml
  go/tools/scion-pki/internal/v2/trcs/testdata/ISD1/trc-v3.toml
  go/tools/scion-pki/internal/v2/trcs/testdata/ISD1/trcs/ISD1-V1.parts/ISD1-V1.prototype
  go/tools/scion-pki/internal/v2/trcs/testdata/ISD1/trcs/ISD1-V2.parts/ISD1-V2.prototype
  go/tools/scion-pki/internal/v2/trcs/testdata/ISD1/trcs/ISD1-V3.parts/ISD1-V3.prototype
  go/tools/scion-pki/internal/v2/trcs/util.go
Labels: PKI-Tool

#3342 SPKI: Remove legacy config definitions
  go/tools/scion-pki/internal/v2/conf/BUILD.bazel
  go/tools/scion-pki/internal/v2/conf/as.go
  go/tools/scion-pki/internal/v2/conf/as_test.go
  go/tools/scion-pki/internal/v2/conf/isd.go
  go/tools/scion-pki/internal/v2/conf/isd_test.go
Labels: PKI-Tool

#3340 SPKI: TRC signing
  go/lib/scrypto/trc/v2/primary.go
  go/tools/scion-pki/internal/pkicmn/pkicmn.go
  go/tools/scion-pki/internal/v2/keys/priv.go
  go/tools/scion-pki/internal/v2/trcs/BUILD.bazel
  go/tools/scion-pki/internal/v2/trcs/cmd.go
  go/tools/scion-pki/internal/v2/trcs/loader.go
  go/tools/scion-pki/internal/v2/trcs/sign.go
  go/tools/scion-pki/internal/v2/trcs/sign_test.go
  go/tools/scion-pki/internal/v2/trcs/testdata/ISD1/trcs/ISD1-V1.parts/ISD1-V1.1-ff00_0_110.sig
  go/tools/scion-pki/internal/v2/trcs/testdata/ISD1/trcs/ISD1-V1.parts/ISD1-V1.1-ff00_0_120.sig
  go/tools/scion-pki/internal/v2/trcs/testdata/ISD1/trcs/ISD1-V1.parts/ISD1-V1.1-ff00_0_130.sig
  go/tools/scion-pki/internal/v2/trcs/testdata/ISD1/trcs/ISD1-V2.parts/ISD1-V2.1-ff00_0_110.sig
  go/tools/scion-pki/internal/v2/trcs/testdata/ISD1/trcs/ISD1-V2.parts/ISD1-V2.1-ff00_0_120.sig
  go/tools/scion-pki/internal/v2/trcs/testdata/ISD1/trcs/ISD1-V3.parts/ISD1-V3.1-ff00_0_120.sig
  go/tools/scion-pki/internal/v2/trcs/testdata/ISD1/trcs/ISD1-V3.parts/ISD1-V3.1-ff00_0_130.sig
  go/tools/scion-pki/internal/v2/trcs/util.go
Labels: PKI-Tool

#3345 SPKI: Add AS and Issuer certificate configuration
  go/tools/scion-pki/internal/v2/conf/BUILD.bazel
  go/tools/scion-pki/internal/v2/conf/as.go
  go/tools/scion-pki/internal/v2/conf/as_test.go
  go/tools/scion-pki/internal/v2/conf/issuer.go
  go/tools/scion-pki/internal/v2/conf/issuer_test.go
  go/tools/scion-pki/internal/v2/conf/key_test.go
  go/tools/scion-pki/internal/v2/conf/main_test.go
  go/tools/scion-pki/internal/v2/conf/testdata/BUILD.bazel
  go/tools/scion-pki/internal/v2/conf/testdata/as-v1.toml
  go/tools/scion-pki/internal/v2/conf/testdata/issuer-v1.toml
  go/tools/scion-pki/internal/v2/conf/testdata/keys.go
  go/tools/scion-pki/internal/v2/conf/testdata/trc.go
  go/tools/scion-pki/internal/v2/conf/trc_test.go
  go/tools/scion-pki/internal/v2/keys/BUILD.bazel
  go/tools/scion-pki/internal/v2/keys/priv_test.go
  go/tools/scion-pki/internal/v2/keys/pub_test.go
Labels: PKI-Tool

#3341 SPKI: TRC signature combination
  go/tools/scion-pki/internal/v2/trcs/BUILD.bazel
  go/tools/scion-pki/internal/v2/trcs/cmd.go
  go/tools/scion-pki/internal/v2/trcs/combine.go
  go/tools/scion-pki/internal/v2/trcs/combine_test.go
  go/tools/scion-pki/internal/v2/trcs/loader.go
  go/tools/scion-pki/internal/v2/trcs/testdata/ISD1/trcs/ISD1-V1.parts/ISD1-V1.1-ff00_0_999.sig
  go/tools/scion-pki/internal/v2/trcs/testdata/ISD1/trcs/ISD1-V1.trc
  go/tools/scion-pki/internal/v2/trcs/testdata/ISD1/trcs/ISD1-V2.trc
  go/tools/scion-pki/internal/v2/trcs/testdata/ISD1/trcs/ISD1-V3.trc
  go/tools/scion-pki/internal/v2/trcs/util.go
  go/tools/scion-pki/internal/v2/trcs/validator.go
Labels: PKI-Tool

#3363 SPKI: Generate issuer and AS config for topo
  go/tools/scion-pki/internal/v2/tmpl/BUILD.bazel
  go/tools/scion-pki/internal/v2/tmpl/topo.go
  go/tools/scion-pki/internal/v2/tmpl/topo_test.go
Labels: PKI-Tool

#3332 Refactor overlay addresses to always use net.IP
  go/beacon_srv/internal/onehop/sender_test.go
  go/border/BUILD.bazel
  go/border/io_test.go
  go/border/rpkt/route.go
  go/godispatcher/main_test.go
  go/godispatcher/network/app_socket.go
  go/godispatcher/network/dispatcher.go
  go/integration/end2end/main.go
  go/lib/hostinfo/hostinfo.go
  go/lib/infra/messenger/addr_test.go
  go/lib/overlay/BUILD.bazel
  go/lib/overlay/addr.go
  go/lib/overlay/conn/BUILD.bazel
  go/lib/overlay/conn/conn.go
  go/lib/snet/router.go
  go/lib/snet/router_test.go
  go/lib/snet/snet.go
  go/lib/snet/writer.go
  go/lib/sock/reliable/reconnect/main_test.go
  go/lib/sock/reliable/reliable.go
  go/lib/svc/svc_test.go
  go/lib/topology/addr.go
  go/lib/topology/addr_test.go
  go/lib/topology/braddr.go
  go/lib/topology/raw.go
  go/lib/topology/topology_test.go
  go/tools/scmp/cmn/common.go
  go/tools/scmp/main.go
Labels: refactor

#3370 Reduce usage of hostinfo.Host
  go/integration/cert_req/BUILD.bazel
  go/integration/cert_req/main.go
  go/lib/addr/appaddr.go
  go/lib/hostinfo/BUILD.bazel
  go/lib/hostinfo/hostinfo.go
  go/lib/infra/modules/itopo/BUILD.bazel
  go/lib/infra/modules/itopo/topology.go
  go/sciond/internal/fetcher/BUILD.bazel
  go/sciond/internal/fetcher/fetcher.go
  go/sciond/internal/servers/handlers.go
  go/sig/egress/session/sessmon.go
  go/sig/internal/base/pollhdlr.go
  go/sig/mgmt/BUILD.bazel
  go/sig/mgmt/addr.go
Labels: refactor

#3384 snet: Split paths to own file, add PathInterface
  go/lib/infra/messenger/BUILD.bazel
  go/lib/infra/messenger/addr_test.go
  go/lib/pathmgr/pathmgr_test.go
  go/lib/pathpol/hop_pred.go
  go/lib/pathpol/pathset.go
  go/lib/pathpol/policy_test.go
  go/lib/pathpol/sequence.go
  go/lib/sciond/mock_sciond/sciond.go
  go/lib/sciond/types.go
  go/lib/snet/BUILD.bazel
  go/lib/snet/mock_snet/BUILD.bazel
  go/lib/snet/mock_snet/snet.go
  go/lib/snet/path.go
  go/lib/snet/router.go
  go/lib/svc/BUILD.bazel
  go/lib/svc/resolver.go
  go/path_srv/internal/segutil/filter.go
  go/sciond/internal/fetcher/filter.go
Labels: refactor

#3427 Simplify topology.TopoAddr, remove topology.TopoBRAddr
  acceptance/topo_br_reload_if_ip_acceptance/test
  acceptance/topo_br_reload_if_port_acceptance/test
  go/beacon_srv/internal/beaconing/originator.go
  go/beacon_srv/internal/beaconing/originator_test.go
  go/beacon_srv/internal/beaconing/propagator.go
  go/beacon_srv/internal/beaconing/registrar_test.go
  go/beacon_srv/internal/keepalive/sender.go
  go/beacon_srv/main.go
  go/border/BUILD.bazel
  go/border/rctrl/ctrl.go
  go/border/rpkt/create.go
  go/border/rpkt/route.go
  go/border/setup-posix.go
  go/border/setup.go
  go/border/setup_test.go
  go/cert_srv/setup.go
  go/lib/discovery/discoverypool/pool.go
  go/lib/discovery/discoverypool/pool_test.go
  go/lib/healthpool/svcinstance/pool.go
  go/lib/healthpool/svcinstance/pool_test.go
  go/lib/infra/modules/itopo/itopo_test.go
  go/lib/infra/modules/itopo/testdata/topo.json
  go/lib/infra/modules/itopo/topology.go
  go/lib/infra/modules/itopo/validate.go
  go/lib/infra/modules/itopo/validate_test.go
  go/lib/infra/modules/trust/BUILD.bazel
  go/lib/infra/modules/trust/trust_test.go
  go/lib/integration/integration.go
  go/lib/topology/BUILD.bazel
  go/lib/topology/addr.go
  go/lib/topology/addr_test.go
  go/lib/topology/braddr.go
  go/lib/topology/doc.go
  go/lib/topology/raw.go
  go/lib/topology/testdata/basic.json
  go/lib/topology/testdata/core.json
  go/lib/topology/topology.go
  go/lib/topology/topology_test.go
  go/lib/topology/topotestutil/BUILD.bazel
  go/lib/topology/topotestutil/topotestutil.go
  go/path_srv/main.go
Labels: refactor

#3434 sciond: Change refresh mechanism to be safer
  go/lib/infra/modules/segfetcher/fetcher.go
  go/lib/infra/modules/segfetcher/request.go
  go/lib/infra/modules/segfetcher/resolver.go
  go/lib/infra/modules/segfetcher/resolver_test.go
  go/sciond/internal/fetcher/BUILD.bazel
  go/sciond/internal/fetcher/fetcher.go
  go/sciond/internal/fetcher/splitter.go
  go/sciond/internal/fetcher/splitter_test.go
Labels: breaking change
