Repository scionproto/scion, pull requests merged in 2019-10, with the labels that each got.

#3177 keyconf: Load keys from PEM
  go/lib/keyconf/BUILD.bazel
  go/lib/keyconf/doc.go
  go/lib/keyconf/doc_test.go
  go/lib/keyconf/key.go
  go/lib/keyconf/key_test.go
  go/lib/scrypto/validity.go
Labels: CPPKI, PKI-Tool

#3208 Segfetcher: Make NextQuery dependent on segments
  acceptance/sig_short_exp_time_acceptance/test
  go/lib/infra/modules/segfetcher/fetcher.go
  go/lib/infra/modules/seghandler/result.go
  go/lib/infra/modules/seghandler/seghandler.go
  go/lib/infra/modules/seghandler/seghandler_test.go
Labels: bug

#3149 TrustStore: Implement crypto provider
  go/lib/infra/modules/trust/v2/BUILD.bazel
  go/lib/infra/modules/trust/v2/export_test.go
  go/lib/infra/modules/trust/v2/internal/decoded/BUILD.bazel
  go/lib/infra/modules/trust/v2/internal/decoded/decode.go
  go/lib/infra/modules/trust/v2/main_test.go
  go/lib/infra/modules/trust/v2/mock_v2/BUILD.bazel
  go/lib/infra/modules/trust/v2/mock_v2/v2.go
  go/lib/infra/modules/trust/v2/provider.go
  go/lib/infra/modules/trust/v2/provider_test.go
  go/lib/infra/modules/trust/v2/recurser.go
  go/lib/infra/modules/trust/v2/testdata/gen_crypto_tar.sh
  tools/gomocks
Labels: CPPKI

#3212 acceptance: Increase reconnect wait time
  acceptance/reconnecting_acceptance/test
Labels: bug

#3213 serrors: Add nogo check
  BUILD.bazel
  WORKSPACE
  go/lib/infra/modules/trust/trust.go
  go/lib/infra/modules/trust/v2/internal/decoded/decode.go
Labels: enhancement

#3204 Fix prometheus code in metrics documentation
  doc/Metrics.md
Labels: documentation

#3211 TrustStore: Implement TRC resolution
  go/lib/infra/modules/trust/testdata/.gitignore
  go/lib/infra/modules/trust/v2/BUILD.bazel
  go/lib/infra/modules/trust/v2/export_test.go
  go/lib/infra/modules/trust/v2/internal/decoded/decode.go
  go/lib/infra/modules/trust/v2/mock_v2/BUILD.bazel
  go/lib/infra/modules/trust/v2/mock_v2/v2.go
  go/lib/infra/modules/trust/v2/resolver.go
  go/lib/infra/modules/trust/v2/resolver_test.go
  go/lib/infra/modules/trust/v2/resolvers.go
  go/lib/infra/modules/trust/v2/rpc.go
  go/lib/scrypto/cert/v2/chain.go
  go/lib/scrypto/trc/v2/signed.go
  tools/gomocks
Labels: CPPKI

#3222 TrustStore: Implement recurser
  go/lib/infra/modules/trust/v2/BUILD.bazel
  go/lib/infra/modules/trust/v2/recurser.go
  go/lib/infra/modules/trust/v2/recurser_test.go
Labels: CPPKI

#3217 SPKI: Add key configuration
  go/lib/util/duration_wrap.go
  go/tools/scion-pki/internal/v2/conf/BUILD.bazel
  go/tools/scion-pki/internal/v2/conf/key.go
  go/tools/scion-pki/internal/v2/conf/key_test.go
  go/tools/scion-pki/internal/v2/conf/testdata/BUILD.bazel
  go/tools/scion-pki/internal/v2/conf/testdata/keys.go
  go/tools/scion-pki/internal/v2/conf/testdata/keys.toml
  go/tools/scion-pki/internal/v2/conf/validity.go
  go/tools/scion-pki/internal/v2/tmpl/BUILD.bazel
  go/tools/scion-pki/internal/v2/tmpl/cmd.go
  go/tools/scion-pki/internal/v2/tmpl/keys.go
  go/tools/scion-pki/internal/v2/tmpl/topo.go
Labels: CPPKI, PKI-Tool

#3223 TrustStore: Add ISD inspector
  go/lib/infra/common.go
  go/lib/infra/modules/trust/v2/BUILD.bazel
  go/lib/infra/modules/trust/v2/export_test.go
  go/lib/infra/modules/trust/v2/inspector.go
  go/lib/infra/modules/trust/v2/inspector_test.go
  go/lib/infra/modules/trust/v2/mock_v2/v2.go
  tools/gomocks
Labels: CPPKI

#3225 TrustStore: Implement inserter
  go/lib/infra/modules/trust/v2/BUILD.bazel
  go/lib/infra/modules/trust/v2/export_test.go
  go/lib/infra/modules/trust/v2/inserter.go
  go/lib/infra/modules/trust/v2/inserter_test.go
  go/lib/infra/modules/trust/v2/router.go
  go/lib/infra/modules/trust/v2/router_test.go
Labels: CPPKI

#3218 SPKI: Generate private keys
  go/lib/keyconf/key.go
  go/lib/keyconf/key_test.go
  go/tools/scion-pki/internal/pkicmn/pkicmn.go
  go/tools/scion-pki/internal/v2/conf/key.go
  go/tools/scion-pki/internal/v2/conf/validity.go
  go/tools/scion-pki/internal/v2/keys/BUILD.bazel
  go/tools/scion-pki/internal/v2/keys/priv.go
  go/tools/scion-pki/internal/v2/keys/priv_test.go
  go/tools/scion-pki/internal/v2/keys/util.go
  go/tools/scion-pki/internal/v2/tmpl/topo.go
Labels: CPPKI, PKI-Tool

#3227 SPKI: Generate public keys
  go/lib/scrypto/BUILD.bazel
  go/lib/scrypto/asym.go
  go/tools/scion-pki/internal/v2/keys/BUILD.bazel
  go/tools/scion-pki/internal/v2/keys/priv.go
  go/tools/scion-pki/internal/v2/keys/pub.go
  go/tools/scion-pki/internal/v2/keys/pub_test.go
Labels: CPPKI, PKI-Tool

#3233 Clean up host type in SCIOND-API RPC messages
  go/integration/cert_req/main.go
  go/lib/hostinfo/hostinfo.go
  go/lib/sciond/types.go
  go/sciond/internal/servers/handlers.go
  go/sig/mgmt/addr.go
Labels: refactor

#3235 segfetcher: Keep next query entries when receiving revocations
  go/lib/infra/modules/segfetcher/fetcher.go
  go/lib/infra/modules/segfetcher/request.go
  go/lib/infra/modules/segfetcher/requester.go
  go/lib/infra/modules/segfetcher/requester_test.go
  go/lib/infra/modules/segfetcher/resolver.go
  go/lib/infra/modules/segfetcher/resolver_test.go
  go/path_srv/internal/handlers/segrevoc.go
  go/sciond/internal/servers/handlers.go
Labels: PS, bug

#3232 PS: Expose request metrics
  go/lib/addr/isdas.go
  go/lib/prom/prom.go
  go/lib/prom/promtest/promtest.go
  go/path_srv/internal/metrics/BUILD.bazel
  go/path_srv/internal/metrics/metrics.go
  go/path_srv/internal/metrics/requests.go
  go/path_srv/internal/metrics/requests_test.go
  go/path_srv/internal/segreq/BUILD.bazel
  go/path_srv/internal/segreq/handler.go
Labels: PS, monitoring

#3244 Simplify SCIOND client API implementation
  go/lib/infra/infraenv/infraenv.go
  go/lib/sciond/BUILD.bazel
  go/lib/sciond/reconn.go
  go/lib/sciond/sciond.go
  go/lib/snet/snet.go
  go/tools/scmp/main.go
  go/tools/showpaths/paths.go
Labels: SNET, refactor

#3250 SD: returns ErrNoPaths if no paths were found
  go/sciond/internal/fetcher/fetcher.go
Labels: SCIOND, bug

#3247 SD: Add request metrics
  go/sciond/internal/metrics/BUILD.bazel
  go/sciond/internal/metrics/metrics.go
  go/sciond/internal/metrics/metrics_test.go
  go/sciond/internal/servers/BUILD.bazel
  go/sciond/internal/servers/handlers.go
Labels: SCIOND, monitoring

#3241 PS: Add segsyncer metrics
  go/lib/prom/prom.go
  go/path_srv/internal/handlers/segreg.go
  go/path_srv/internal/handlers/segsync.go
  go/path_srv/internal/metrics/BUILD.bazel
  go/path_srv/internal/metrics/metrics.go
  go/path_srv/internal/metrics/registration.go
  go/path_srv/internal/metrics/sync.go
  go/path_srv/internal/metrics/sync_test.go
  go/path_srv/internal/segreq/handler.go
  go/path_srv/internal/segsyncer/BUILD.bazel
  go/path_srv/internal/segsyncer/segsyncer.go
  go/sciond/internal/metrics/metrics.go
Labels: PS, monitoring

#3254 Add metrics for SCIOND client API
  go/lib/sciond/BUILD.bazel
  go/lib/sciond/internal/metrics/BUILD.bazel
  go/lib/sciond/internal/metrics/metrics.go
  go/lib/sciond/sciond.go
Labels: SCIOND, enhancement, monitoring

#3243 HP: Add HPSegReqHandler
  go/hidden_path_srv/internal/hpsegreq/BUILD.bazel
  go/hidden_path_srv/internal/hpsegreq/fetcher.go
  go/hidden_path_srv/internal/hpsegreq/fetcher_test.go
  go/hidden_path_srv/internal/hpsegreq/handler.go
  go/hidden_path_srv/internal/hpsegreq/handler_test.go
  go/hidden_path_srv/internal/hpsegreq/mock_hpsegreq/BUILD.bazel
  go/hidden_path_srv/internal/hpsegreq/mock_hpsegreq/hpsegreq.go
  go/hidden_path_srv/internal/hpsegreq/registry_algo.go
  go/hidden_path_srv/internal/hpsegreq/registry_algo_test.go
  go/lib/addr/host.go
  go/lib/infra/messenger/messenger.go
  tools/gomocks
Labels: HP

#3259 Remove old messenger metrics implementation
  go/lib/infra/infraenv/infraenv.go
  go/lib/infra/messenger/BUILD.bazel
  go/lib/infra/messenger/messenger_with_metrics.go
  go/lib/infra/messenger/messenger_with_metrics_test.go
Labels: refactor

#3257 Add metrics to snet
  go/lib/snet/BUILD.bazel
  go/lib/snet/dispatcher.go
  go/lib/snet/internal/metrics/BUILD.bazel
  go/lib/snet/internal/metrics/metrics.go
  go/lib/snet/packet_conn.go
  go/lib/snet/snet.go
Labels: SNET, enhancement, monitoring

#3258 Add metrics to the Go dispatcher
  go/godispatcher/internal/metrics/BUILD.bazel
  go/godispatcher/internal/metrics/metrics.go
  go/godispatcher/internal/respool/packet.go
  go/godispatcher/network/app_socket.go
  go/godispatcher/network/dispatcher.go
  go/godispatcher/network/overlay.go
  go/godispatcher/network/table.go
  go/lib/scmp/scmp.go
Labels: Dispatcher, enhancement, monitoring

#3262 PS: Add metrics for revocation notifications
  go/lib/prom/prom.go
  go/path_srv/internal/handlers/segrevoc.go
  go/path_srv/internal/metrics/BUILD.bazel
  go/path_srv/internal/metrics/metrics.go
  go/path_srv/internal/metrics/revocation.go
  go/path_srv/internal/metrics/revocation_test.go
  go/sciond/internal/metrics/metrics.go
Labels: PS, monitoring

#3260 HP: Add HPGCfgReqHandler
  go/hidden_path_srv/internal/hpcfgreq/BUILD.bazel
  go/hidden_path_srv/internal/hpcfgreq/handler.go
  go/hidden_path_srv/internal/hpcfgreq/handler_test.go
Labels: HP

#3266 Fix wrong git checkout path in README
  README.md
Labels: documentation

#3273 Improve messenger metrics
  go/lib/infra/disp/disp.go
  go/lib/infra/disp/disp_test.go
  go/lib/infra/messenger/BUILD.bazel
  go/lib/infra/messenger/adapter.go
  go/lib/infra/messenger/internal/metrics/BUILD.bazel
  go/lib/infra/messenger/internal/metrics/metrics.go
  go/lib/infra/messenger/internal/metrics/metrics_test.go
  go/lib/infra/messenger/messenger.go
  go/lib/prom/prom.go
Labels: enhancement, monitoring

#3272 segfetcher: Classify error better
  go/lib/infra/modules/segfetcher/BUILD.bazel
  go/lib/infra/modules/segfetcher/fetcher.go
  go/lib/infra/modules/segfetcher/metrics.go
  go/lib/infra/modules/segfetcher/resolver.go
  go/path_srv/internal/handlers/segsync.go
  go/path_srv/internal/segreq/handler.go
  go/path_srv/internal/segreq/provider.go
  go/path_srv/internal/segreq/splitter.go
  go/path_srv/internal/segreq/validator.go
  go/sciond/internal/metrics/metrics.go
  go/sciond/internal/servers/handlers.go
Labels: monitoring

#3264 segfetcher: Add segreq & revocation metrics
  go/lib/infra/modules/segfetcher/BUILD.bazel
  go/lib/infra/modules/segfetcher/fetcher.go
  go/lib/infra/modules/segfetcher/internal/metrics/BUILD.bazel
  go/lib/infra/modules/segfetcher/internal/metrics/fetcher.go
  go/lib/infra/modules/segfetcher/internal/metrics/fetcher_test.go
  go/lib/infra/modules/segfetcher/internal/metrics/metrics.go
  go/lib/infra/modules/seghandler/BUILD.bazel
  go/lib/infra/modules/seghandler/result.go
  go/lib/infra/modules/seghandler/seghandler.go
  go/path_srv/internal/metrics/revocation.go
  go/path_srv/internal/segreq/handler.go
  go/proto/structs.gen.go
  go/sciond/internal/fetcher/BUILD.bazel
  go/sciond/internal/fetcher/fetcher.go
  go/sciond/internal/metrics/metrics.go
Labels: monitoring
