Repository scionproto/scion, pull requests merged in 2019-07, with the labels that each got.

#2840 PS: Dedupe reply verification as well
  go/path_srv/internal/handlers/psdedupe.go
  go/path_srv/internal/handlers/segreq.go
Labels: PS

#2842 crypto: Introduce validity period
  go/lib/scrypto/BUILD.bazel
  go/lib/scrypto/validity.go
  go/lib/scrypto/validity_test.go
  go/lib/util/BUILD.bazel
  go/lib/util/time.go
  go/lib/util/time_test.go
Labels: CPPKI

#2847 crypto: TRC format
  go/lib/scrypto/trc/v2/BUILD.bazel
  go/lib/scrypto/trc/v2/doc.go
  go/lib/scrypto/trc/v2/keychanges.go
  go/lib/scrypto/trc/v2/pop.go
  go/lib/scrypto/trc/v2/primary.go
  go/lib/scrypto/trc/v2/primary_json_test.go
  go/lib/scrypto/trc/v2/primary_test.go
  go/lib/scrypto/trc/v2/trc.go
  go/lib/scrypto/trc/v2/trc_json_test.go
  go/lib/scrypto/trc/v2/trc_test.go
Labels: CPPKI

#2860 crypto: TRC update validation
  go/lib/scrypto/trc/v2/BUILD.bazel
  go/lib/scrypto/trc/v2/keychanges.go
  go/lib/scrypto/trc/v2/primary.go
  go/lib/scrypto/trc/v2/update.go
  go/lib/scrypto/trc/v2/update_test.go
Labels: CPPKI

#2899 TRC: Add update signature verification
  go/lib/scrypto/trc/v2/BUILD.bazel
  go/lib/scrypto/trc/v2/primary_json_test.go
  go/lib/scrypto/trc/v2/primary_test.go
  go/lib/scrypto/trc/v2/signed.go
  go/lib/scrypto/trc/v2/trc_json_test.go
  go/lib/scrypto/trc/v2/trc_test.go
  go/lib/scrypto/trc/v2/update_test.go
  go/lib/scrypto/trc/v2/verify.go
  go/lib/scrypto/trc/v2/verify_test.go
Labels: CPPKI

#2912 scrpto: Move KeyMeta + Version
  go/lib/scrypto/BUILD.bazel
  go/lib/scrypto/keymeta.go
  go/lib/scrypto/keymeta_test.go
  go/lib/scrypto/trc/v2/keychanges.go
  go/lib/scrypto/trc/v2/pop.go
  go/lib/scrypto/trc/v2/primary.go
  go/lib/scrypto/trc/v2/primary_json_test.go
  go/lib/scrypto/trc/v2/primary_test.go
  go/lib/scrypto/trc/v2/signed.go
  go/lib/scrypto/trc/v2/signed_test.go
  go/lib/scrypto/trc/v2/trc.go
  go/lib/scrypto/trc/v2/trc_json_test.go
  go/lib/scrypto/trc/v2/trc_test.go
  go/lib/scrypto/trc/v2/update_test.go
  go/lib/scrypto/validity.go
  go/lib/scrypto/validity_test.go
  go/lib/scrypto/version.go
  go/lib/scrypto/version_test.go
Labels: CPPKI

#2910 cert: Add base certificate
  go/lib/scrypto/cert/v2/BUILD.bazel
  go/lib/scrypto/cert/v2/base.go
  go/lib/scrypto/cert/v2/base_json_test.go
  go/lib/scrypto/cert/v2/base_test.go
  go/lib/scrypto/trc/v2/trc.go
  go/lib/scrypto/validity.go
Labels: CPPKI

#2914 HP: Add HP messages to the messenger
  go/lib/infra/common.go
  go/lib/infra/messenger/messenger.go
  go/lib/infra/messenger/messenger_with_metrics.go
  go/lib/infra/messenger/messenger_with_metrics_test.go
  go/lib/infra/messenger/quic_response_writer.go
  go/lib/infra/messenger/udp_response_writer.go
  go/lib/infra/mock_infra/infra.go
Labels: HP

#2921 BS: Ignore inactive interfaces in Propagator/Registrar
  go/beacon_srv/internal/beaconing/extender.go
  go/beacon_srv/internal/beaconing/propagator.go
  go/beacon_srv/internal/beaconing/registrar.go
Labels: BS

#2934 CS: Do not retry core push immediately
  go/cert_srv/internal/reiss/corepush.go
Labels: CS

#2927 scrypto: Make map keys integers
  go/lib/scrypto/cert/v2/base.go
  go/lib/scrypto/cert/v2/base_json_test.go
  go/lib/scrypto/trc/v2/primary.go
  go/lib/scrypto/trc/v2/primary_json_test.go
  go/lib/scrypto/trc/v2/signed_json_test.go
Labels: CPPKI

#2936 cert: Add AS certificate
  go/lib/scrypto/cert/v2/BUILD.bazel
  go/lib/scrypto/cert/v2/as.go
  go/lib/scrypto/cert/v2/as_json_test.go
  go/lib/scrypto/cert/v2/as_test.go
  go/lib/scrypto/cert/v2/base.go
  go/lib/scrypto/cert/v2/base_json_test.go
Labels: CPPKI

#2931 HP: hidden path group structure
  go/lib/ctrl/path_mgmt/hp_cfg.go
  go/lib/hiddenpath/BUILD.bazel
  go/lib/hiddenpath/group.go
  go/lib/hiddenpath/group_test.go
Labels: HP

#2945 sciond: Add method to filter paths with a policy
  go/lib/pathpol/acl.go
  go/lib/pathpol/acl_test.go
  go/lib/pathpol/hop_pred.go
  go/lib/pathpol/policy_test.go
  go/sciond/internal/fetcher/BUILD.bazel
  go/sciond/internal/fetcher/filter.go
  go/sciond/internal/fetcher/filter_test.go
Labels: sciond
