Repository scionproto/scion, pull requests merged in 2020-05, with the labels that each got.

#3744 improve contribution guide
  CONTRIBUTING.md
  README.md
  doc/build/setup.rst
  doc/contribute.rst
  doc/contribute/bazel-style.rst
  doc/contribute/git.rst
  doc/contribute/go-learn.rst
  doc/contribute/go-style.rst
  doc/contribute/json-style.rst
  doc/contribute/python-style.rst
  doc/contribute/rst-style.rst
  doc/contribute/toml-style.rst
  doc/cryptography/index.rst
  doc/index.rst
Labels: documentation

#3748 Remove dead code related to segment requests
  go/cs/segreq/BUILD.bazel
  go/cs/segreq/db.go
  go/cs/segreq/db_test.go
  go/cs/segreq/handler.go
  go/cs/segreq/mock_segreq/BUILD.bazel
  go/cs/segreq/mock_segreq/segreq.go
  go/cs/segreq/validator_test.go
  go/lib/infra/modules/segfetcher/BUILD.bazel
  go/lib/infra/modules/segfetcher/fetcher.go
  go/lib/infra/modules/segfetcher/fetcher_test.go
  go/lib/infra/modules/segfetcher/mock_segfetcher/BUILD.bazel
  go/lib/infra/modules/segfetcher/mock_segfetcher/segfetcher.go
  go/lib/infra/modules/segfetcher/validator.go
  tools/gomocks
Labels: enhancement

#3752 Add COLIBRI E2E application level types
  go/cs/reservation/e2e/BUILD.bazel
  go/cs/reservation/e2e/index.go
  go/cs/reservation/e2e/reservation.go
  go/cs/reservation/e2e/reservation_test.go
  go/cs/reservation/index.go
  go/cs/reservation/segment/BUILD.bazel
  go/cs/reservation/segment/export_test.go
  go/cs/reservation/segment/path_test.go
  go/cs/reservation/segment/reservation.go
  go/cs/reservation/segment/reservation_test.go
  go/cs/reservation/segmenttest/BUILD.bazel
  go/cs/reservation/segmenttest/common.go
  go/lib/colibri/reservation/types.go
Labels: enhancement

#3760 Add specifications for SCION and Extension Headers.
  doc/extension-header.rst
  doc/index.rst
  doc/scion-header.rst
Labels: documentation

#3771 remove unused path resolver from snet.NewNetwork
  go/border/rctrl/ctrl.go
  go/examples/pingpong/pingpong.go
  go/integration/common.go
  go/lib/infra/infraenv/infraenv.go
  go/lib/sciond/pathprobe/paths.go
  go/lib/snet/conn.go
  go/lib/snet/snet.go
  go/lib/snet/writer.go
  go/sig/internal/sigcmn/common.go
Labels: breaking change
