Repository scionproto/scion, pull requests merged in 2020-04, with the labels that each got.

#3716 dispatcher: drop implementation language from name
  BUILD.bazel
  acceptance/brutil/docker-compose.yml
  acceptance/sig_failover/BUILD.bazel
  acceptance/sig_short_exp_time/BUILD.bazel
  acceptance/topo_cs_reload/BUILD.bazel
  acceptance/topo_sd_reload/BUILD.bazel
  docker/perapp/BUILD.bazel
  docker/perapp/README.md
  docker/perapp/publish
  go/dispatcher/BUILD.bazel
  go/dispatcher/config/BUILD.bazel
  go/dispatcher/config/config.go
  go/dispatcher/config/config_test.go
  go/dispatcher/config/sample.go
  go/dispatcher/dispatcher/BUILD.bazel
  go/dispatcher/dispatcher/dispatcher.go
  go/dispatcher/dispatcher/overlay.go
  go/dispatcher/dispatcher/overlay_test.go
  go/dispatcher/dispatcher/scmp.go
  go/dispatcher/dispatcher/table.go
  go/dispatcher/internal/metrics/BUILD.bazel
  go/dispatcher/internal/metrics/metrics.go
  go/dispatcher/internal/registration/BUILD.bazel
  go/dispatcher/internal/registration/bench_test.go
  go/dispatcher/internal/registration/errors.go
  go/dispatcher/internal/registration/generators_test.go
  go/dispatcher/internal/registration/iatable.go
  go/dispatcher/internal/registration/iatable_test.go
  go/dispatcher/internal/registration/portlist.go
  go/dispatcher/internal/registration/portlist_test.go
  go/dispatcher/internal/registration/scmp_table.go
  go/dispatcher/internal/registration/scmp_table_test.go
  go/dispatcher/internal/registration/svctable.go
  go/dispatcher/internal/registration/svctable_test.go
  go/dispatcher/internal/registration/table.go
  go/dispatcher/internal/registration/table_test.go
  go/dispatcher/internal/registration/udptable.go
  go/dispatcher/internal/registration/udptable_test.go
  go/dispatcher/internal/respool/BUILD.bazel
  go/dispatcher/internal/respool/buffer.go
  go/dispatcher/internal/respool/packet.go
  go/dispatcher/main.go
  go/dispatcher/main_test.go
  go/dispatcher/network/BUILD.bazel
  go/dispatcher/network/app_socket.go
  go/dispatcher/network/dispatcher.go
  go/sig/internal/sigcmn/BUILD.bazel
  go/sig/internal/sigcmn/common.go
  python/topology/docker.py
  python/topology/sig.py
  python/topology/supervisor.py
Labels: breaking change

#3708 scion: one command to rule them all
  BUILD.bazel
  go.mod
  go.sum
  go/pkg/showpaths/BUILD.bazel
  go/pkg/showpaths/config.go
  go/pkg/showpaths/showpaths.go
  go/scion/BUILD.bazel
  go/scion/completion.go
  go/scion/scion.go
  go/scion/showpaths.go
  go/scion/version.go
  go_deps.bzl
Labels: enhancement, tooling

#3734 Initialize RTD project for documentation site
  .gitignore
  doc/Makefile
  doc/conf.py
  doc/index.rst
  doc/make.bat
Labels: documentation

#3736 remove segment synchronization from PS docs
  doc/PathService.md
Labels: documentation

#3741 topology: simplify format
  acceptance/br_child_acceptance/conf/topology.json
  acceptance/br_core_childIf_acceptance/conf/topology.json
  acceptance/br_core_coreIf_acceptance/conf/topology.json
  acceptance/br_core_multi_acceptance/conf/topology.json
  acceptance/br_multi_acceptance/conf/topology.json
  acceptance/br_parent_acceptance/conf/topology.json
  acceptance/br_peer_acceptance/conf/topology.json
  acceptance/bs_add_link_acceptance/test
  acceptance/common.sh
  acceptance/topo_br_reload_if_ip_acceptance/test
  acceptance/topo_br_reload_if_port_acceptance/test
  acceptance/topo_br_reload_rollback_acceptance/test
  acceptance/topo_common/BUILD.bazel
  acceptance/topo_common/topology.json
  acceptance/topo_cs_reload/BUILD.bazel
  acceptance/topo_cs_reload/testdata/topology_reload.json
  acceptance/topo_sd_reload/testdata/topology_reload.json
  go/border/testdata/topology.json
  go/cs/beaconing/testdata/topology-core.json
  go/cs/beaconing/testdata/topology.json
  go/cs/handlers/testdata/topology_as1_132.json
  go/cs/handlers/testdata/topology_as2_211.json
  go/cs/handlers/testdata/topology_as2_222.json
  go/cs/ifstate/testdata/topology.json
  go/cs/keepalive/testdata/topology.json
  go/lib/infra/modules/itopo/internal/metrics/metrics.go
  go/lib/infra/modules/itopo/itopo.go
  go/lib/infra/modules/itopo/itopo_test.go
  go/lib/infra/modules/itopo/testdata/topo.json
  go/lib/infra/modules/itopo/validate_test.go
  go/lib/topology/export_test.go
  go/lib/topology/json/BUILD.bazel
  go/lib/topology/json/json.go
  go/lib/topology/json/json_test.go
  go/lib/topology/json/testdata/topology.json
  go/lib/topology/raw.go
  go/lib/topology/testdata/basic.json
  go/lib/topology/testdata/core.json
  go/lib/topology/topology.go
  go/lib/topology/topology_test.go
  python/topology/common.py
  python/topology/docker.py
  python/topology/go.py
  python/topology/prometheus.py
  python/topology/supervisor.py
  python/topology/topo.py
Labels: breaking change

#3742 add documentation for x.509 cryptography
  doc/contribute.rst
  doc/cryptography/ca-operations.rst
  doc/cryptography/certificates.rst
  doc/cryptography/crypto_lib.sh
  doc/cryptography/fig
  doc/cryptography/index.rst
  doc/cryptography/interactions.rst
  doc/cryptography/standards.rst
  doc/cryptography/trc-signing-ceremony-phases.rst
  doc/cryptography/trc-signing-ceremony-preparations.rst
  doc/cryptography/trc-signing-ceremony.rst
  doc/cryptography/trc.rst
  doc/cryptography/trc_ceremony.sh
  doc/index.rst
  scripts/cryptoplayground/BUILD.bazel
  scripts/cryptoplayground/crypto_lib.sh
  scripts/cryptoplayground/gen_certs.sh
  scripts/cryptoplayground/openssl.cnf
  scripts/cryptoplayground/trc_ceremony.sh
Labels: CPPKI, documentation
