Repository scionproto/scion, pull requests merged in 2020-01, with the labels that each got.

#3571 Remove path resolution step from snet writes
  go/lib/snet/BUILD.bazel
  go/lib/snet/export_test.go
  go/lib/snet/internal/ctxmonitor/BUILD.bazel
  go/lib/snet/internal/ctxmonitor/ctxmonitor.go
  go/lib/snet/internal/ctxmonitor/ctxmonitor_test.go
  go/lib/snet/internal/ctxmonitor/mock_ctxmonitor/BUILD.bazel
  go/lib/snet/internal/ctxmonitor/mock_ctxmonitor/ctxmonitor.go
  go/lib/snet/mock_snet/snet.go
  go/lib/snet/snet.go
  go/lib/snet/writer.go
  go/lib/snet/writer_test.go
  tools/gomocks
Labels: breaking change

#3587 SPKI: Fix template generation
  go/tools/scion-pki/internal/v2/tmpl/topo.go
  go/tools/scion-pki/internal/v2/tmpl/topo_test.go
Labels: bug

#3599 Clean up pipeline file names
  .buildkite/pipeline.sh
  .buildkite/pipeline.yml
Labels: refactor

#3600 Add bazel icon to bazelified pipeline tests
  .buildkite/pipeline.sh
  .buildkite/pipeline.yml
Labels: devops

#3607 Add primary attributes to topology file
  acceptance/br_child_acceptance/conf/topology.json
  acceptance/br_core_childIf_acceptance/conf/topology.json
  acceptance/br_core_coreIf_acceptance/conf/topology.json
  acceptance/br_core_multi_acceptance/conf/topology.json
  acceptance/br_multi_acceptance/conf/topology.json
  acceptance/br_parent_acceptance/conf/topology.json
  acceptance/br_peer_acceptance/conf/topology.json
  acceptance/topo_invalid_reloads_acceptance/test
  go/cs/beaconing/testdata/topology-core.json
  go/cs/beaconing/testdata/topology.json
  go/cs/handlers/testdata/topology_as1_132.json
  go/cs/handlers/testdata/topology_as2_211.json
  go/cs/handlers/testdata/topology_as2_222.json
  go/cs/ifstate/testdata/topology.json
  go/cs/keepalive/testdata/topology.json
  go/lib/infra/modules/itopo/BUILD.bazel
  go/lib/infra/modules/itopo/testdata/topo.json
  go/lib/infra/modules/itopo/validate.go
  go/lib/infra/modules/itopo/validate_test.go
  go/lib/scrypto/trc/primary.go
  go/lib/topology/BUILD.bazel
  go/lib/topology/interface.go
  go/lib/topology/json/BUILD.bazel
  go/lib/topology/json/json.go
  go/lib/topology/json/json_test.go
  go/lib/topology/json/testdata/topology.json
  go/lib/topology/testdata/basic.json
  go/lib/topology/testdata/core.json
  go/lib/topology/topology.go
  go/lib/topology/topology_test.go
  python/lib/topology.py
  python/test/lib/topology_test.py
  python/topology/topo.py
Labels: breaking change

#3631 Use snet.{UDP,SVC}Addr instead of snet.Addr everywhere
  go/cs/beaconing/handler.go
  go/cs/beaconing/handler_test.go
  go/cs/handlers/segreg.go
  go/cs/handlers/segsync.go
  go/cs/keepalive/handler.go
  go/cs/keepalive/handler_test.go
  go/examples/pingpong/pingpong.go
  go/hidden_path_srv/internal/hpcfgreq/handler.go
  go/hidden_path_srv/internal/hpcfgreq/handler_test.go
  go/hidden_path_srv/internal/hpsegreq/fetcher.go
  go/hidden_path_srv/internal/hpsegreq/fetcher_test.go
  go/hidden_path_srv/internal/hpsegreq/handler.go
  go/hidden_path_srv/internal/hpsegreq/handler_test.go
  go/hidden_path_srv/internal/hpsegreq/mock_hpsegreq/hpsegreq.go
  go/hidden_path_srv/internal/registration/handler.go
  go/hidden_path_srv/internal/registration/handler_test.go
  go/integration/cert_req/main.go
  go/integration/common.go
  go/integration/end2end/main.go
  go/lib/infra/messenger/addr.go
  go/lib/infra/messenger/messenger.go
  go/lib/infra/modules/trust/recurser.go
  go/lib/sciond/pathprobe/paths.go
  go/lib/snet/BUILD.bazel
  go/lib/snet/addr.go
  go/lib/snet/reader.go
  go/lib/snet/svcaddr.go
  go/lib/snet/udpaddr.go
  go/lib/snet/udpaddr_test.go
  go/lib/sock/reliable/reconnect/conn_io_test.go
  go/lib/sock/reliable/reconnect/main_test.go
  go/lib/sock/reliable/reconnect/network_test.go
  go/sig/internal/disp/disp.go
  go/sig/internal/ingress/BUILD.bazel
  go/sig/internal/ingress/dispatcher.go
  go/sig/internal/ingress/worker.go
  go/sig/internal/ingress/worker_test.go
  go/tools/scmp/cmn/BUILD.bazel
  go/tools/scmp/cmn/common.go
  go/tools/scmp/main.go
  go/tools/scmp/traceroute/BUILD.bazel
  go/tools/scmp/traceroute/traceroute.go
  go/tools/showpaths/paths.go
Labels: refactor
